---
title: "deepfri_analysis"
output: html_document
---

```{r import}
library(dplyr)
setwd("/Users/oliviatatro/Downloads/surf/deepfri")

load("deepfri50.Rdata")
print("deepfri loaded")

focal_nodes <- data.frame(
    node = c(132, 133, 103, 104, 129, 
             130, 105, 116, 163, 159, 
             134, 137, 120, 108, 102, 
             150,   2,  22,  87,  88, 
             90,   74,  42,  11, 106,
             114, 117, 121, 122, 164, 
             166, 135, 136, 138, 139,
             140,  99, 100, 101),
    name = c("anth", "anth2", "endomed", "med", "endo", 
             "myx", "hyd", "acr", "oct", "cer", 
             "hex", "scler", "scyph", "siph", "cnid", 
             "act", "acropora", "nematostella", "hydra", "clytia",
             "turritopsis", "aurelia", "xenia", "stylophora", "106",
             "114", "117", "121", "122", "164", 
             "166", "135", "136", "138", "139",
             "140", "myr", "plan", "eum"),
    full_name = c("Anthozoa", "Ceriantheria + Hexacorallia", "Endocnidozoa + Medusozoa", "Medusozoa", "Endocnidozoa",
                  "Myxozoa", "Hydrozoa", "Acraspeda", "Octocorallia", "Ceriantheria", 
                  "Hexacorallia", "Scleractinia", "Scyphozoa", "Siphonophora", "Cnidaria",
                  "Actinaria", "Acropora", "Nematostella", "Hydra", "Clytia", 
                  "Turritopsis", "Aurelia", "Xenia", "Stylophora", "106",
                  "114", "117", "121", "122", "164", 
                  "166", "135", "136", "138", "139",
                  "140", "Myriazoa", "Planulozoa", "Eumetazoa")
    )

node_cols <- c("#E7468E", "#e34a32","#DA71FE", "#4991FE", "#8E10D2",
               "#590D8F",  "#2448D8", "#2ED9FF", "#9e021c", "#9bcc1f",
               "#fa7e18","#0a7d23","#1FD295", "#0e0c70","#e08dc9",
               "#e3af02", "grey20", "grey20","grey20","grey20",
               "grey20","grey20","grey20","grey20", "grey20",
               "grey20","grey20","grey20","grey20", "grey20",
               "grey20","grey20","grey20","grey20", "grey20",
               "grey20", "grey20","grey20","grey20")
node_cols_full <- node_cols
names(node_cols) <- focal_nodes$name
names(node_cols_full) <- focal_nodes$full_name


load("../orthodollo/tree.Rds")
tree <- tr1
rm(tr1)
print("tree loaded")

load("../orthodollo/loss_gain_pres_abs_H1.Rds")
gl <- lossgain.table
rm(lossgain.table)
print("lossgain loaded")

```

Data manip to get the df into the same format as eggnog: 
 - node
 - gained GO terms (comma separated)
 - lost GO terms (comma separated)
```{r setup}

gl <- as.data.frame(t(gl))
colnames(gl) <- as.character(1:ncol(gl))
gl$og <- rownames(gl)
print("gl prepped")

og_summary <- data.frame(node = character(), event = character(), og = character())

for (node in 98:193) {
  print(node)
  gained <- gl[gl[[node]] == "g", node, drop = FALSE] 
  gained <- data.frame(og = rownames(gained))
  if(nrow(gained) > 0) {
    gained$node <- node
    gained$event <- "gain"
    og_summary <- rbind(og_summary, gained)
  }
  
  lost <- gl[gl[[node]] == "l", node, drop = FALSE] 
  lost <- data.frame(og = rownames(lost))
  if(nrow(lost) > 0) {
    lost$node <- node
    lost$event <- "lost"
    og_summary <- rbind(og_summary, lost)
  }
}

write.table(og_summary, file = "og_summary.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

# goal: node event og

bp_OG_GO <- bp %>% mutate(og = sub("_.*", "", Protein)) %>% 
  dplyr::select(og, GO) %>% 
  group_by(og) %>% 
  summarize(GOs = paste(GO, collapse = ","), .groups = "drop")
table(strsplit(bp_OG_GO$GOs[1], ","))
print("bp collapsed")

cc_OG_GO <- cc %>% mutate(og = sub("_.*", "", Protein)) %>% 
  dplyr::select(og, GO) %>% 
  group_by(og) %>% 
  summarize(GOs = paste(GO, collapse = ","), .groups = "drop")
table(strsplit(cc_OG_GO$GOs[1], ","))
print("cc collapsed")

mf_OG_GO <- mf %>% mutate(og = sub("_.*", "", Protein)) %>% 
  dplyr::select(og, GO) %>% 
  group_by(og) %>% 
  summarize(GOs = paste(GO, collapse = ","), .groups = "drop")
table(strsplit(mf_OG_GO$GOs[1], ","))
print("mf collapsed")

bp_GOs <- data.frame(node = character(), g_GOs = vector(), l_GOs = vector())
cc_GOs <- data.frame(node = character(), g_GOs = vector(), l_GOs = vector())
mf_GOs <- data.frame(node = character(), g_GOs = vector(), l_GOs = vector())

for (NODE in 1:193) {
  
  if (NODE %in% focal_nodes$node) {
    print(paste("starting node: ", NODE))

    gained <- gl[gl[[NODE]] == "g", NODE, drop = FALSE] 
    gained$og <- rownames(gained) 
    lost <- gl[gl[[NODE]] == "l", NODE, drop = FALSE] 
    lost$og <- rownames(lost) 
  
    #bp
    gained_GOs <- merge(bp_OG_GO, gained) %>% select(-og) %>% group_by(!!sym(as.character(NODE))) %>% 
      summarize(GOs = paste(GOs, collapse = ","), .groups = "drop")
    lost_GOs <- merge(bp_OG_GO, lost) %>% select(-og) %>% group_by(!!sym(as.character(NODE))) %>% 
      summarize(GOs = paste(GOs, collapse = ","), .groups = "drop")
  
    bp_GOs <- rbind(bp_GOs, data.frame(node = NODE, g_GOs = I(list(strsplit(gained_GOs$GOs[1], ",")[[1]])), l_GOs = I(list(strsplit(lost_GOs$GOs[1], ",")[[1]]))))
  
    #cc
    gained_GOs <- merge(cc_OG_GO, gained) %>% select(-og) %>% group_by(!!sym(as.character(NODE))) %>% 
      summarize(GOs = paste(GOs, collapse = ","), .groups = "drop")
    lost_GOs <- merge(cc_OG_GO, lost) %>% select(-og) %>% group_by(!!sym(as.character(NODE))) %>% 
      summarize(GOs = paste(GOs, collapse = ","), .groups = "drop")
    cc_GOs <- rbind(cc_GOs, data.frame(node = NODE, g_GOs = I(list(strsplit(gained_GOs$GOs[1], ",")[[1]])), l_GOs = I(list(strsplit(lost_GOs$GOs[1], ",")[[1]]))))
  
    #mf
    gained_GOs <- merge(mf_OG_GO, gained) %>% select(-og) %>% group_by(!!sym(as.character(NODE))) %>% 
      summarize(GOs = paste(GOs, collapse = ","), .groups = "drop")
    lost_GOs <- merge(mf_OG_GO, lost) %>% select(-og) %>% group_by(!!sym(as.character(NODE))) %>% 
      summarize(GOs = paste(GOs, collapse = ","), .groups = "drop")
    mf_GOs <- rbind(mf_GOs, data.frame(node = NODE, g_GOs = I(list(strsplit(gained_GOs$GOs[1], ",")[[1]])), l_GOs = I(list(strsplit(lost_GOs$GOs[1], ",")[[1]]))))
  }
  else {
  print(paste("Skipping node:", NODE))
  bp_GOs <- rbind(bp_GOs, data.frame(node = NODE, g_GOs = NA, l_GOs = NA))
  cc_GOs <- rbind(cc_GOs, data.frame(node = NODE, g_GOs = NA, l_GOs = NA))
  mf_GOs <- rbind(mf_GOs, data.frame(node = NODE, g_GOs = NA, l_GOs = NA))
  }
}

print("setup done")

```

```{r GO_setup}

safe_fisher <- function(a, b, c, d) {
  mat <- matrix(c(a, b - a, c, d - c), nrow = 2, byrow = TRUE)
  if (any(mat < 0) || any(is.na(mat)) || any(!is.finite(mat))) return(1)
  fisher.test(mat, alternative = "greater")$p.value
}

GO_setup <- function(DATA, NODE) {
  
  gains <- DATA$g_GOs[[NODE]]
  losses <- DATA$l_GOs[[NODE]]
  
  # take a row of the GOs dataframe and make count tables with each GO term and how many are in gains and losses (may need to do this separately and then cbind)
  if (all(is.na(gains))) {
    g_counts <- data.frame(GO_term = character(), gained = numeric())
  } else {
    g_counts <- as.data.frame(table(gains))
    colnames(g_counts) <- c("GO_term", "gained")
  }

  if (all(is.na(losses))) {
    l_counts <- data.frame(GO_term = character(), lost = numeric())
  } else {
    l_counts <- as.data.frame(table(losses))
    colnames(l_counts) <- c("GO_term", "lost")
  }
  #g_counts <- as.data.frame(table(DATA[NODE,2]))
  #colnames(g_counts) <- c("GO_term", "gained")
  #l_counts <- as.data.frame(table(DATA[NODE,3]))
  #colnames(l_counts) <- c("GO_term", "lost")
  
  GO_counts <- merge(g_counts, l_counts, by = "GO_term", all = TRUE)
  GO_counts$GO_term <- factor(GO_counts$GO_term, levels = GO_counts$GO_term)
  GO_counts$gained <- ifelse(is.na(GO_counts$gained), 0, GO_counts$gained)
  GO_counts$lost <- ifelse(is.na(GO_counts$lost), 0, GO_counts$lost)
  
  total_gains <- sum(GO_counts$gained)
  total_losses <- sum(GO_counts$lost)
  GO_counts$prop_gained <- GO_counts$gained / total_gains
  GO_counts$prop_lost <- GO_counts$lost / total_losses
  GO_counts$diff <- GO_counts$gained - GO_counts$lost
  GO_counts$prop_diff <- GO_counts$prop_gained - GO_counts$prop_lost
  GO_counts$sum <- GO_counts$gained + GO_counts$lost
  
  if(nrow(filter(GO_counts, gained != 0)) != 0) {
    # fishertest: IF EACH GO TERM IS GAINED MORE IN NODE THAN IN OTHER NODES
    # a = number of GO_term gains in anthozoa
    # b = number of other GO terms gained in anthozoa
    # c = number of GO_term gains in other nodes
    # d = number of other GO term gains in other nodes 
    b = as.numeric(length(DATA[[NODE,2]]))
    all_GO_gains <- unlist(DATA$g_GOs, recursive = TRUE)
    d = as.numeric(length(all_GO_gains))
    all_GO_gain_counts <- table(all_GO_gains)
    
    GO_counts <- GO_counts %>% 
  	filter(!is.na(GO_term) & grepl("^GO:", GO_term))
    
    GO_counts$pval_gain <- apply(GO_counts, 1, function(row) {
      a <- as.numeric(row["gained"])
      go <- row[["GO_term"]]
      c <- as.numeric(all_GO_gain_counts[go])
      #mat <- matrix(c(a,b-a,c,d-c),nrow = 2, byrow = TRUE)
      #fisher.test(mat, alternative = "greater")$p.value
      safe_fisher(a,b,c,d)
    })
    GO_counts$padj_gain <- p.adjust(GO_counts$pval_gain, method = "bonferroni")
  }  
  if(nrow(filter(GO_counts, lost != 0)) != 0) {
    # fishertest: IF EACH GO TERM IS LOST MORE IN NODE THAN IN OTHER NODES
    # a = number of GO_term losses in anthozoa
    # b = number of other GO terms lost in anthozoa
    # c = number of GO_term losses in other nodes
    # d = number of other GO term losses in other nodes 
    b = as.numeric(length(DATA[[NODE,3]]))
    all_GO_losses <- unlist(DATA$l_GOs, recursive = TRUE)
    d = as.numeric(length(all_GO_losses))
    all_GO_loss_counts <- table(all_GO_losses)
    
    GO_counts$pval_loss <- apply(GO_counts, 1, function(row) {
      a <- as.numeric(row["lost"])
      go <- row[["GO_term"]]
      c <- as.numeric(all_GO_loss_counts[go])
      #mat <- matrix(c(a,b-a,c,d-c),nrow = 2, byrow = TRUE)
      #fisher.test(mat, alternative = "greater")$p.value
      safe_fisher(a,b,c,d)
    })
    GO_counts$padj_loss <- p.adjust(GO_counts$pval_loss, method = "bonferroni")
  }
  
  
  return(GO_counts)
}
print("GO setup initialized")

```

```{r GO_figure_tsvs}
process <- function(NODE, DIR) {
  dir.create(DIR)
  GO_df <- GO_setup(bp_GOs, NODE)
  GO_df <- GO_df %>% mutate(padj_loss = if_else(padj_loss == 0, 1e-300, padj_loss),
			    padj_gain = if_else(padj_gain == 0, 1e-300, padj_gain))
  write.table(GO_df, file.path(DIR, "BP_GO_df.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  if(nrow(filter(GO_df, gained != 0)) == 0){
    print(paste("No BP gains in node: ", NODE))
  } else {
    gain <- GO_df %>% 
      dplyr::select(c("GO_term", "padj_gain", "gained"))
    write.table(gain, file.path(DIR, "BP_gain.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
	#write_tsv(gain, file.path(DIR, "BP_gain.tsv"), col_names = FALSE)
  }
  if(nrow(filter(GO_df, lost != 0)) == 0){
    print(paste("No BP losses in node: ", NODE))
  } else {
    loss <- GO_df %>% 
      dplyr::select(c("GO_term", "padj_loss", "lost"))  
    #write_tsv(loss, file.path(DIR, "BP_loss.tsv"), col_names = FALSE)
    write.table(loss, file.path(DIR, "BP_loss.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  }
  
  GO_df <- GO_setup(cc_GOs, NODE)
  GO_df <- GO_df %>% mutate(padj_loss = if_else(padj_loss == 0, 1e-300, padj_loss),
                            padj_gain = if_else(padj_gain == 0, 1e-300, padj_gain))
  write.table(GO_df, file.path(DIR, "CC_GO_df.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  if(nrow(filter(GO_df, gained != 0)) == 0){
    print(paste("No CC gains in node: ", NODE))
  } else {
    gain <- GO_df %>% 
      dplyr::select(c("GO_term", "padj_gain", "gained"))  
      #filter(padj_gain <= 0.01) %>% 
      #mutate(padj_gain = if_else(padj_gain == 0, 1e-300, padj_gain))
    write.table(gain, file.path(DIR, "CC_gain.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
    #write_tsv(gain, file.path(DIR, "CC_gain.tsv"), col_names = FALSE)
  }
  if(nrow(filter(GO_df, lost != 0)) == 0){
    print(paste("No CC losses in node: ", NODE))
  } else {
    loss <- GO_df %>% 
      dplyr::select(c("GO_term", "padj_loss", "lost"))  
      #filter(padj_loss <= 0.01) %>% 
      #mutate(padj_loss = if_else(padj_loss == 0, 1e-300, padj_loss))
    #write_tsv(loss, file.path(DIR, "CC_loss.tsv"), col_names = FALSE)
    write.table(loss, file.path(DIR, "CC_loss.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  }
  
  GO_df <- GO_setup(mf_GOs, NODE)
  GO_df <- GO_df %>% mutate(padj_loss = if_else(padj_loss == 0, 1e-300, padj_loss),
                            padj_gain = if_else(padj_gain == 0, 1e-300, padj_gain))
  write.table(GO_df, file.path(DIR, "MF_GO_df.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  if(nrow(filter(GO_df, gained != 0)) == 0){
    print(paste("No MF gains in node: ", NODE))
  } else {
    gain <- GO_df %>% 
      dplyr::select(c("GO_term", "padj_gain", "gained"))  
      #filter(padj_gain <= 0.01) %>% 
      #mutate(padj_gain = if_else(padj_gain == 0, 1e-300, padj_gain))
    write.table(gain, file.path(DIR, "MF_gain.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
    #write_tsv(gain, file.path(DIR, "MF_gain.tsv"), col_names = FALSE)
  }
  if(nrow(filter(GO_df, lost != 0)) == 0){
    print(paste("No MF losses in node: ", NODE))
  } else {
    loss <- GO_df %>% 
      dplyr::select(c("GO_term", "padj_loss", "lost")) 
      #filter(padj_loss <= 0.01) %>% 
      #mutate(padj_loss = if_else(padj_loss == 0, 1e-300, padj_loss))
    #write_tsv(loss, file.path(DIR, "MF_loss.tsv"), col_names = FALSE)
    write.table(loss, file.path(DIR, "MF_loss.tsv"),
                sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  }
}
print("process initialized")

dir="go_figure_tsvs50"

dir.create(dir)

for (i in 1:nrow(focal_nodes)) {
  print(paste("processing node:", focal_nodes$number[i]))
  process(focal_nodes$number[i], file.path(dir,focal_nodes$name[i]))
}

print("gofigure setup done")

```


```{r GO_figure_replot, message=FALSE, warning=FALSE, eval = FALSE}
library(ggforce)
library(dplyr)
library(readr)
library(this.path)
setwd(this.dir())
library(cowplot)


focal_nodes <- data.frame(node_number = c(132, 133, 103, 104, 129, 130, 105, 116, 163, 159, 134, 137, 120, 108, 102), node_name = c("anth", "anth2", "endomed", "med", "endo", "myx", "hyd", "acr", "oct", "cer", "hex", "scler", "scyph", "siph", "cnid"))



dir <- "/Users/oliviatatro/Downloads/surf/deepfri/go_figure_tsvs50"

named_colors <- c(`Other / Unclassified` = "grey25",
                  `Behavior, Movement, & Environmental Response` = "firebrick4", 
                  `Cell Communication & Signaling` = "#994C00", 
                  `Cell Cycle & Division` = "#666600",
                  `Cellular Transport & Localization` = "#006633",
                  `Development & Morphogenesis` = "#006666",
                  `Gene Expression & Regulation` = "#003366",
                  `Immune & Defense Response` = "#4B0082",
                  `Metabolism & Biosynthesis` = "violetred4",
                  `Cytoplasm & Cytosol` = "red",
                  `Cytoskeleton & Cell Junctions` = "chocolate1",
                  `Endomembrane System & Vesicles` = "#C4FF3B",
                  `Extracellular Region & Matrix` = "green3",
                  `Membrane-Bound Organelles` = "turquoise3",
                  `Nucleus & Chromatin` = "dodgerblue3",
                  `Plasma Membrane & Cell Periphery` = "darkviolet",
                  `Synapse & Specialized Structure` = "#FF3BC4",
                  `Binding (Small Molecule, Ion, Cofactor)` = "#FF9999",
                  `Catalytic Activity` = "#FFB266",
                  `Molecular Adaptors & Modulators` = "#FFFF99",
                  `Motor & Mechanical Activity` = "darkolivegreen2",
                  `Signal Transduction Activity` = "#99FFCC",
                  `Structural Molecule Activity` = "#99CCFF",
                  `Transcription Regulator Activity` = "#CC99FF",
                  `Transporter Activity` = "#FF99CC")

# PLOT FUNCTION ----------------------------------------------------------------
#DOTS <- file.path(dir, paste0(focal_nodes$node_name[1], "_gain"), paste0("biological_process_output_", focal_nodes$node_name[1], "_gain.tsv"))
#CATS <- "/Users/oliviatatro/Downloads/surf/eggnog/go_figure/BP_classified.csv" 
#TITLE <- "anth"


bp_cats <- read.table("/Users/oliviatatro/Downloads/surf/GO_classifications/BP_categorized.tsv", sep = "\t", header = TRUE)
cc_cats <- read.table("/Users/oliviatatro/Downloads/surf/GO_classifications/CC_categorized.tsv", sep = "\t", header = TRUE)
mf_cats <- read.table("/Users/oliviatatro/Downloads/surf/GO_classifications/MF_categorized.tsv", sep = "\t", header = TRUE)


TITLE <- "test"
transform <- function(num) {
  return((-log10(num)/300)^(1/2)) # range: 0 to 1
}
ROW <- 1

gofigure_data <- data.frame(description = character(), x = numeric(), y = numeric(), pval = numeric(), category = character(), size = numeric(), node = character(), event = character())

ontologies <- data.frame(full = c("biological_process_", "cellular_component_", "molecular_function_"), abr = c("bp", "cc", "mf"), file = c("bp_cats", "cc_cats", "mf_cats"))

for (row in 1:nrow(focal_nodes)) {
  for (ont in 1:nrow(ontologies)) {
    for (event in c("gain", "loss")) {
      filepath <- file.path(dir, focal_nodes$node_name[row], event, paste0(ontologies$full[ont], "go_figure_tsvs50_", focal_nodes$node_name[row], "_", event, ".tsv"))
      if (file.exists(filepath)) {
        dots <- as.data.frame(read_tsv(filepath)) %>% 
          merge(get(ontologies$file[ont]), by = "description") %>% 
          mutate(node = focal_nodes$node_name[row], event = event, ontology = ontologies$abr[ont]) %>% 
          dplyr::select(c(description, x, y, pval, user, category, node, event, ontology)) %>%
          dplyr::rename(size = "user")
        gofigure_data <- rbind(gofigure_data, dots)
      }
    }
  }
}

NODE = "anth"
EVENT = "gain"

gofigureplot <- function(NODE, EVENT, DATA) {
  dots <- DATA %>% filter(node == NODE, event == EVENT) 
  plot <- ggplot() +
    geom_circle(data = filter(dots, pval >= 0.01), aes(x0 = x, y0 = y, r = log(size)/30, fill = I("grey70"), col = I("grey70")), stroke = 0.1, alpha = 0.3) +
    geom_circle(data = filter(dots, pval < 0.01), aes(x0 = x, y0 = y, r = log(size)/30, fill = category, col = category), stroke = 0.1, alpha = 0.7) +
    ggtitle(paste(NODE, EVENT)) +
    scale_fill_manual(values = named_colors) +
    scale_color_manual(values = named_colors) +
    scale_x_continuous(limits = c(-2,2)) +
    scale_y_continuous(limits = c(-2,2)) +
    theme_void() +
    theme(legend.position = "none",
          axis.title = element_blank(),
          panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
          plot.margin = margin(t = 10, r = 10, b = 10, l = 10, unit = "pt"))
  return(plot) 
}

plots <- list()

#gofigureplot("anth", "gain", gofigure_data)
for (node in focal_nodes$node_name) {
  for (event in c("gain", "loss")) {
    print(paste(node, event))
    plots[[paste(node, event)]] <- gofigureplot(node, event, gofigure_data)
  }
}


# LEGEND ----
categories <- names(named_colors)
dots <- data.frame(description = paste0("des_", seq_along(categories)), x = 1, y = seq_along(categories) * 2, size = 0.88, pval = 1, category = factor(categories, levels = categories))
legend_dots <- 
  ggplot(dots) +
  geom_circle(aes(x0 = x, y0 = y, r = size, fill = category, col = category), alpha = 0.7) +
  scale_fill_manual(values = named_colors) + #, guide = guide_legend(ncol = 1)
  scale_color_manual(values = named_colors) +
  theme_void() +
  theme(legend.position = "none") +
  scale_x_continuous(limits = c(0,2)) +
  scale_y_continuous(limits = c(1,51))
legend_text <- 
  ggplot(dots) +
  geom_text(aes(y = y, label = category), x = 0, hjust = 0, cex = 3) +
  theme_void() +
  theme(legend.position = "none") +
  scale_x_continuous(limits = c(0,1.05)) +
  scale_y_continuous(limits = c(1,51))
legend <- plot_grid(legend_dots, legend_text, nrow = 1, rel_widths = c(0.5, 4.5))

pdf("../figures/deepfri_go_50_24.pdf", width = 22, height = 15)

bubbles <- plot_grid(plotlist = plots, nrow = 5)
fig <- plot_grid(bubbles, legend, rel_widths = c(18,4))
print(fig)

dev.off()
```




```{r GO_figure_replot, message=FALSE, warning=FALSE}
library(ggforce)
library(dplyr)
library(readr)
library(this.path)
setwd(this.dir())
library(cowplot)
library(tidyr)

focal_nodes <- data.frame(node_number = c(132, 133, 103, 104, 129, 130, 105, 116, 163, 159, 134, 137, 120, 108, 102), node_name = c("anth", "anth2", "endomed", "med", "endo", "myx", "hyd", "acr", "oct", "cer", "hex", "scler", "scyph", "siph", "cnid"))

dir <- "/Users/oliviatatro/Downloads/surf/deepfri/go_figure_tsvs50"

named_colors <- c(`Behavior, Movement, & Environmental Response` = "firebrick4", 
                  `Cell Communication & Signaling` = "#994C00", 
                  `Cell Cycle & Division` = "#666600",
                  `Cellular Transport & Localization` = "#006633",
                  `Development & Morphogenesis` = "#006666",
                  `Gene Expression & Regulation` = "#003366",
                  `Immune & Defense Response` = "#4B0082",
                  `Metabolism & Biosynthesis` = "violetred4",
                  `Cytoplasm & Cytosol` = "red",
                  `Cytoskeleton & Cell Junctions` = "chocolate1",
                  `Endomembrane System & Vesicles` = "#C4FF3B",
                  `Extracellular Region & Matrix` = "green3",
                  `Membrane-Bound Organelles` = "turquoise3",
                  `Nucleus & Chromatin` = "dodgerblue3",
                  `Plasma Membrane & Cell Periphery` = "darkviolet",
                  `Specialized Structure` = "#FF3BC4",
                  `Binding (Small Molecule, Ion, Cofactor)` = "#FF9999",
                  `Catalytic Activity` = "#FFB266",
                  `Molecular Adaptors & Modulators` = "#FFFF99",
                  `Motor & Mechanical Activity` = "darkolivegreen2",
                  `Signal Transduction Activity` = "#99FFCC",
                  `Structural Molecule Activity` = "#99CCFF",
                  `Transcription Regulator Activity` = "#CC99FF",
                  `Transporter Activity` = "#FF99CC")





# PLOT FUNCTION ----------------------------------------------------------------
#DOTS <- file.path(dir, paste0(focal_nodes$node_name[1], "_gain"), paste0("biological_process_output_", focal_nodes$node_name[1], "_gain.tsv"))
#CATS <- "/Users/oliviatatro/Downloads/surf/eggnog/go_figure/BP_classified.csv" 
#TITLE <- "anth"


cats <- read.table("/Users/oliviatatro/Downloads/surf/GO_classifications/categories.tsv", sep = "\t", header = TRUE)

gofigure_data <- data.frame(description = character(), x = numeric(), y = numeric(), pval = numeric(), category = character(), size = numeric(), node = character(), event = character(), members = character())

ontologies <- data.frame(full = c("biological_process_", "cellular_component_", "molecular_function_"), abr = c("bp", "cc", "mf"))

for (row in 1:nrow(focal_nodes)) {
  for (ont in 1:nrow(ontologies)) {
    for (event in c("gain", "loss")) {
      filepath <- file.path(dir, focal_nodes$node_name[row], event, paste0(ontologies$full[ont], "go_figure_tsvs50_", focal_nodes$node_name[row], "_", event, ".tsv"))
      if (file.exists(filepath)) {
        dots <- as.data.frame(read_tsv(filepath)) %>% 
          merge(cats, by = "description") %>% 
          mutate(node = focal_nodes$node_name[row], event = event, ontology = ontologies$abr[ont]) %>% 
          dplyr::select(c(description, x, y, pval, user, category, node, event, ontology, members)) %>%
          dplyr::rename(size = "user")
        gofigure_data <- rbind(gofigure_data, dots)
      }
    }
  }
}

write.table(gofigure_data, file = "go_figure_data.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

go_des <- gofigure_data %>% select(c(description, category, members)) %>% separate_rows(members, sep = ", ") %>% 
  mutate(members = gsub("'", "", members)) %>% 
  mutate(members = gsub("\\[", "", members)) %>% 
  mutate(members = gsub("\\]", "", members)) %>% 
  unique()
  
write.table(go_des, file="go_term_descriptions.tsv", row.names = FALSE, quote = TRUE, sep = "\t")

unique(sort(gofigure_data$category))

gofigureplot <- function(NODE, EVENT, DATA) {
  dots <- DATA %>% filter(node == NODE, event == EVENT) 
  plot <- ggplot() +
    geom_circle(data = filter(dots, pval >= 0.01), aes(x0 = x, y0 = y, r = log(size)/30, fill = I("grey70"), col = I("grey70")), stroke = 0.1, alpha = 0.3) +
    geom_circle(data = filter(dots, pval < 0.01), aes(x0 = x, y0 = y, r = log(size)/30, fill = category, col = category), stroke = 0.1, alpha = 0.7) +
    ggtitle(paste(NODE, EVENT)) +
    scale_fill_manual(values = named_colors) +
    scale_color_manual(values = named_colors) +
    scale_x_continuous(limits = c(-2.5,2.5)) +
    scale_y_continuous(limits = c(-2.5,2.5)) +
    theme_void() +
    theme(legend.position = "none",
          axis.title = element_blank(),
          panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
          plot.margin = margin(t = 10, r = 10, b = 10, l = 10, unit = "pt"))
  return(plot) 
}

plots <- list()

#gofigureplot("anth", "gain", gofigure_data)
for (node in focal_nodes$node_name) {
  for (event in c("gain", "loss")) {
    print(paste(node, event))
    plots[[paste(node, event)]] <- gofigureplot(node, event, gofigure_data)
  }
}


# LEGEND ----
categories <- names(named_colors)
dots <- data.frame(description = paste0("des_", seq_along(categories)), x = 1, y = seq_along(categories) * 2, size = 0.88, pval = 1, category = factor(categories, levels = categories))
legend_dots <- 
  ggplot(dots) +
  geom_circle(aes(x0 = x, y0 = y, r = size, fill = category, col = category), alpha = 0.7) +
  scale_fill_manual(values = named_colors) + #, guide = guide_legend(ncol = 1)
  scale_color_manual(values = named_colors) +
  theme_void() +
  theme(legend.position = "none") +
  scale_x_continuous(limits = c(0,2)) +
  scale_y_continuous(limits = c(1,51))
legend_text <- 
  ggplot(dots) +
  geom_text(aes(y = y, label = category), x = 0, hjust = 0, cex = 3) +
  theme_void() +
  theme(legend.position = "none") +
  scale_x_continuous(limits = c(0,1.05)) +
  scale_y_continuous(limits = c(1,51))
legend <- plot_grid(legend_dots, legend_text, nrow = 1, rel_widths = c(0.5, 4.5))

#pdf("../figures/deepfri_go_50.pdf", width = 22, height = 15)

bubbles <- plot_grid(plotlist = plots, nrow = 5)
fig <- plot_grid(bubbles, legend, rel_widths = c(18,4))
print(fig)

#dev.off()
```


```{r GO_figure_data_summary_all_nodes}
library(ggforce)
library(dplyr)
library(readr)
library(this.path)
setwd(this.dir())
library(cowplot)
library(tidyr)

dir <- "/Users/oliviatatro/Downloads/surf/deepfri/go_figure_tsvs"

named_colors <- c(`Behavior, Movement, & Environmental Response` = "firebrick4", 
                  `Cell Communication & Signaling` = "#994C00", 
                  `Cell Cycle & Division` = "#666600",
                  `Cellular Transport & Localization` = "#006633",
                  `Development & Morphogenesis` = "#006666",
                  `Gene Expression & Regulation` = "#003366",
                  `Immune & Defense Response` = "#4B0082",
                  `Metabolism & Biosynthesis` = "violetred4",
                  `Cytoplasm & Cytosol` = "red",
                  `Cytoskeleton & Cell Junctions` = "chocolate1",
                  `Endomembrane System & Vesicles` = "#C4FF3B",
                  `Extracellular Region & Matrix` = "green3",
                  `Membrane-Bound Organelles` = "turquoise3",
                  `Nucleus & Chromatin` = "dodgerblue3",
                  `Plasma Membrane & Cell Periphery` = "darkviolet",
                  `Specialized Structure` = "#FF3BC4",
                  `Binding (Small Molecule, Ion, Cofactor)` = "#FF9999",
                  `Catalytic Activity` = "#FFB266",
                  `Molecular Adaptors & Modulators` = "#FFFF99",
                  `Motor & Mechanical Activity` = "darkolivegreen2",
                  `Signal Transduction Activity` = "#99FFCC",
                  `Structural Molecule Activity` = "#99CCFF",
                  `Transcription Regulator Activity` = "#CC99FF",
                  `Transporter Activity` = "#FF99CC")





# PLOT FUNCTION ----------------------------------------------------------------
#DOTS <- file.path(dir, paste0(focal_nodes$node_name[1], "_gain"), paste0("biological_process_output_", focal_nodes$node_name[1], "_gain.tsv"))
#CATS <- "/Users/oliviatatro/Downloads/surf/eggnog/go_figure/BP_classified.csv" 
#TITLE <- "anth"


cats <- read.table("/Users/oliviatatro/Downloads/surf/GO_classifications/categories.tsv", sep = "\t", header = TRUE)

gofigure_data <- data.frame(description = character(), x = numeric(), y = numeric(), pval = numeric(), category = character(), size = numeric(), node = character(), event = character(), members = character())

ontologies <- c("biological_process_", "cellular_component_", "molecular_function_")
names(ontologies) <- c("bp", "cc", "mf")

for (node in 98:193) {
  for (ont in names(ontologies)) {
    for (event in c("gain", "loss")) {
      filepath <- file.path(dir, node, event, paste0(ontologies[ont], "go_figure_tsvs_", node, "_", event, ".tsv"))
      if (file.exists(filepath)) {
        dots <- as.data.frame(read_tsv(filepath)) %>% 
          merge(cats, by = "description") %>% 
          mutate(node = node, event = event, ontology = ont) %>% 
          dplyr::select(c(description, x, y, pval, user, category, node, event, ontology, members)) %>%
          dplyr::rename(size = "user")
        gofigure_data <- rbind(gofigure_data, dots)
      }
    }
  }
}

# this is being written for go_figure_parse.py (/mnt/home/plachetzki/omt1027/surf/97_taxa/orthofinder_run/deepfri/go_figure/parse_output/go_figure_parse.py)
write.table(gofigure_data, file = "go_figure_data.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```


```{r enrichment_barplots}
library(dplyr)
library(this.path)
library(ggplot2)
setwd(this.dir())
library(ggtext)
library(forcats)

gl_counts <- read.table("function_gl.tsv", header = TRUE, sep = "\t")

gl_counts <- gl_counts %>% filter(node >= 102 & node <= 172) # Filter to include nodes within cnidaria

all_gains <- sum(gl_counts$gain)
all_losses <- sum(gl_counts$loss)

# find total gains and losses for each category and node
gl_counts <- gl_counts %>% group_by(category) %>% 
  mutate(all_cat_gains = sum(gain), all_cat_losses = sum(loss)) %>% ungroup() %>% 
  group_by(node) %>% 
  mutate(all_node_gains = sum(gain), all_node_losses = sum(loss)) %>% ungroup()

# adding columns for the background values needed for the fisher exact test
gl_counts <- gl_counts %>% 
  mutate(non_cat_node_gains = all_node_gains - gain, # gains in the node but not category
         non_cat_node_losses = all_node_losses - loss,  # losses in the node but not category
         non_node_cat_gains = all_cat_gains - gain, # gains in category but not node
         non_node_cat_losses = all_cat_losses - loss, # losses in category but not node 
         non_cat_non_node_gains = all_gains - all_cat_gains - all_node_gains + gain, # gains not in category or node
         non_cat_non_node_losses = all_losses - all_cat_losses - all_node_losses + loss) # losses not in category or node
        

# fisher exact to see if there are more gains at a certain category in each node
# matrix:
#     [,1]                  [,2]                     
#[1,] "loss"                "non_cat_node_losses"    
#[2,] "non_node_cat_losses" "non_cat_non_node_losses"
# writing this in a for loop because mutate gave an FEXACT error due to it storing all the matrices at once
gl_counts$pval_gain <- NA
gl_counts$pval_loss <- NA
gl_counts$fold_gain <- (gl_counts$gain / gl_counts$all_node_gains) / (gl_counts$all_cat_gains / all_gains)
gl_counts$fold_loss <- (gl_counts$loss / gl_counts$all_node_losses) / (gl_counts$all_cat_losses / all_losses)
for (row in 1:nrow(gl_counts)) {
  a <- gl_counts$gain[row]
  b <- gl_counts$non_cat_node_gains[row]
  c <- gl_counts$non_node_cat_gains[row]
  d <- gl_counts$non_cat_non_node_gains[row]
  ft <- fisher.test(matrix(c(a,b,c,d), nrow = 2, byrow = TRUE), alternative = "greater")
  gl_counts$pval_gain[row] <- ft$p.value
  gl_counts$or_gain[row]   <- ft$estimate 
  
  a <- gl_counts$loss[row]
  b <- gl_counts$non_cat_node_losses[row]
  c <- gl_counts$non_node_cat_losses[row]
  d <- gl_counts$non_cat_non_node_losses[row]
  ft <- fisher.test(matrix(c(a,b,c,d), nrow = 2, byrow = TRUE), alternative = "greater")
  gl_counts$pval_loss[row] <- ft$p.value
  gl_counts$or_loss[row]   <- ft$estimate 
}

summary <- gl_counts %>% select(category, gain, loss) %>% 
  group_by(category) %>% 
  summarize(sum_gain = sum(gain),
            sum_loss = sum(loss))

write.table(summary, file = "go_category_summary.tsv", sep = "\t", row.names = FALSE)

gl_counts <- gl_counts %>% filter(node %in% focal_nodes[1:16,]$node) # filter out non focal nodes because we are not using those tests 
gl_counts <- gl_counts %>% mutate(padj_gain = p.adjust(pval_gain, method = "BH"),
                                  padj_loss = p.adjust(pval_loss, method = "BH")) %>% 
  select(category, node, gain, loss, padj_gain, padj_loss, or_gain, or_loss, fold_gain, fold_loss)


gl_counts <- merge(gl_counts, focal_nodes, by = "node")

gl_counts <- gl_counts %>% filter(name %in% c("anth", "anth2", "endomed", "med", "endo", "myx", "hyd", "acr", "oct", "cer", "hex", "scler", "scyph", "siph", "cnid", "act"))

gl_counts$sig_gain <- ifelse(gl_counts$padj_gain < 0.05, gl_counts$gain, 0)
gl_counts$sig_loss <- ifelse(gl_counts$padj_loss < 0.05, gl_counts$loss, 0)
gl_counts$sig_or_gain <- ifelse(gl_counts$padj_gain < 0.05, gl_counts$or_gain, 0)
gl_counts$sig_or_loss <- ifelse(gl_counts$padj_loss < 0.05, gl_counts$or_loss, 0)
gl_counts$sig_fold_gain <- ifelse(gl_counts$padj_gain < 0.05, gl_counts$fold_gain, 0)
gl_counts$sig_fold_loss <- ifelse(gl_counts$padj_loss < 0.05, gl_counts$fold_loss, 0)

x_axis_order <- c("Endocnidozoa", "Myxozoa", "Endocnidozoa + Medusozoa", "Medusozoa", "Hydrozoa", "Siphonophora", "Acraspeda", "Scyphozoa", "Cnidaria", "Anthozoa", "Octocorallia", "Ceriantheria + Hexacorallia", "Hexacorallia", "Actinaria", "Ceriantheria","Scleractinia")
gl_counts$full_name <- factor(gl_counts$full_name, levels = x_axis_order)

write.table(gl_counts, file = "gl_counts.tsv", sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE)
#gl_counts$category <- gsub("Environmental Response", "Environmental Resp.", gl_counts$category)

plot_barplot <- function(gl_counts, cat) {
  min <- -1 * max(gl_counts$loss)
  max <- max(gl_counts$gain)
  barplot <- ggplot(filter(gl_counts, category == cat)) +
    geom_bar(aes(x = full_name, y = gain), fill = "grey70", stat = "identity") +
    geom_bar(aes(x = full_name, y = -loss), fill = "grey70", stat = "identity") +
    geom_bar(aes(x = full_name, y = sig_gain, fill = name), stat = "identity") +
    geom_bar(aes(x = full_name, y = -sig_loss, fill = name), stat = "identity") +
    geom_hline(yintercept = 0, linetype = "dashed") +
    scale_fill_manual(values = node_cols) +
    ylab("Number of OrthoGroups") +
    xlab(NULL) +
    #scale_y_continuous(limits = c(min, max)) +
    scale_x_discrete(
      labels = function(x) {
        paste0("<span style='color:", node_cols_full[x], "'>", x, "</span>") # chatgpt line to make the x axis text match the node colors
      }
    ) +
    ggtitle(cat) +
    theme_bw() +
    theme(axis.text.x = element_markdown(angle = 45, hjust = 1, size = 14, face = "bold"), # need to use element_markdown after the custom colors line,
          axis.text.y = element_text(size = 12),
          axis.title.y = element_text(size = 14),
          plot.title = element_text(size = 15.5, hjust = 0.5),
          legend.position = "none") 
  
  print(barplot)
  return(barplot)
}

plots <- list()
for (cat in unique(gl_counts$category)) {
  plots[[cat]] <- plot_barplot(gl_counts, cat)
}

for (plot_num in 1:24) {
  if (!plot_num %in% c(23,18,24,1)) {
    plots[[plot_num]] <- plots[[plot_num]] + theme(axis.text.x = element_blank())
  }
  if (!plot_num %in% c(2,8,14,21,22,23)) {
    plots[[plot_num]] <- plots[[plot_num]] + ylab(NULL)
  } else {
    plots[[plot_num]] <- plots[[plot_num]] + theme(plot.margin = margin(5.5,4,5.5,30))
  }
}

row1 <- cowplot::plot_grid(plotlist = plots[c(2,4,5,12)], nrow = 1, rel_widths = c(1.12,1,1,1))
row2 <- cowplot::plot_grid(plotlist = plots[c(8,6,7,9)], nrow = 1, rel_widths = c(1.12,1,1,1))
row3 <- cowplot::plot_grid(plotlist = plots[c(14,10,11,3)], nrow = 1, rel_widths = c(1.12,1,1,1))
row4 <- cowplot::plot_grid(plotlist = plots[c(21,13,15,17)], nrow = 1, rel_widths = c(1.12,1,1,1))
row5 <- cowplot::plot_grid(plotlist = plots[c(22,16,19,20)], nrow = 1, rel_widths = c(1.12,1,1,1))
row6 <- cowplot::plot_grid(plotlist = plots[c(23,18,24,1)], nrow = 1, rel_widths = c(1.12,1,1,1))
#row7 <- cowplot::plot_grid(plotlist = plots[19:21], nrow = 1, rel_widths = c(1.12,1,1))
#row8 <- cowplot::plot_grid(plotlist = plots[22:24], nrow = 1, rel_widths = c(1.12,1,1))

cowplot::plot_grid(row1, row2, row3, row4, row5, row6,
                           nrow = 6, ncol = 1, rel_heights = c(1,1,1,1,1,1.6))

dir.create("figures")
#ggsave("figures/enrichment_barplots_6_25_26.png", width = 20, height = 22)




### making Anthozoa plot for the URC slideshow
gl_counts <- read.table("gl_counts.tsv", sep = "\t", header = TRUE)

anth_gl <- gl_counts %>% filter(full_name == "Anthozoa") %>% 
  mutate(category = fct_reorder(category, fold_gain))

ggplot(anth_gl) +
    geom_bar(aes(y = category, x = fold_gain), fill = "grey50", stat = "identity") +
    #geom_bar(aes(y = category, x = -or_loss), fill = "grey50", stat = "identity") +
    geom_bar(aes(y = category, x = sig_fold_gain), fill = "green2", stat = "identity") +
    #geom_bar(aes(y = category, x = -sig_or_loss), fill = "dodgerblue2", stat = "identity") +
    #geom_vline(xintercept = 0, linetype = "dashed") +
    ylab(NULL) +
    xlab("Fold enrichment") +
    ggtitle("Functions of Anthozoan gained genes") +
    theme_bw() +
    theme(axis.text.x = element_markdown(size = 12, color = "white"), # need to use element_markdown after the custom colors line,
          axis.text.y = element_text(size = 10, color = "white"),
          axis.title.y = element_text(size = 14, color = "white"),
          axis.title.x = element_text(size = 14, color = "white"),
          plot.title = element_text(size = 18, hjust = 2, color = "white"),
          legend.position = "none", 
          panel.background = element_rect(fill = "black"),
          panel.border = element_rect(color = "black", fill = NA),
          plot.background  = element_rect(fill = "black"),
          panel.grid.major = element_line(color = "grey25"),
          panel.grid.minor = element_line(color = "grey15")) 

ggsave("figures/anthozoa_gain_enrichment.png", width = 7, height = 5)

```

```{r fisher_cluster_analysis}

library(dplyr)
library(this.path)
library(ggplot2)
setwd(this.dir())
library(ggtext)
library(forcats)

# grabbing this file from /mnt/home/plachetzki/omt1027/surf/97_taxa/orthofinder_run/deepfri/go_figure/parse_output/shiny/go_figure_parse.py
gl_counts <- read.table("cluster_gl.tsv", header = TRUE, sep = "\t")

gl_counts <- gl_counts %>% filter(node >= 102 & node <= 172) # Filter to include nodes within cnidaria

all_gains <- sum(gl_counts$gain)
all_losses <- sum(gl_counts$loss)

# find total gains and losses for each category and node
gl_counts <- gl_counts %>% group_by(category) %>% 
  mutate(all_cat_gains = sum(gain), all_cat_losses = sum(loss)) %>% ungroup() %>% 
  group_by(node) %>% 
  mutate(all_node_gains = sum(gain), all_node_losses = sum(loss)) %>% ungroup()

# adding columns for the background values needed for the fisher exact test
gl_counts <- gl_counts %>% 
  mutate(non_cat_node_gains = all_node_gains - gain, # gains in the node but not category
         non_cat_node_losses = all_node_losses - loss,  # losses in the node but not category
         non_node_cat_gains = all_cat_gains - gain, # gains in category but not node
         non_node_cat_losses = all_cat_losses - loss, # losses in category but not node 
         non_cat_non_node_gains = all_gains - all_cat_gains - all_node_gains + gain, # gains not in category or node
         non_cat_non_node_losses = all_losses - all_cat_losses - all_node_losses + loss) # losses not in category or node
        

# fisher exact to see if there are more gains at a certain category in each node
# matrix:
#     [,1]                  [,2]                     
#[1,] "loss"                "non_cat_node_losses"    
#[2,] "non_node_cat_losses" "non_cat_non_node_losses"
# writing this in a for loop because mutate gave an FEXACT error due to it storing all the matrices at once
gl_counts$pval_gain <- NA
gl_counts$pval_loss <- NA
gl_counts$fold_gain <- (gl_counts$gain / gl_counts$all_node_gains) / (gl_counts$all_cat_gains / all_gains)
gl_counts$fold_loss <- (gl_counts$loss / gl_counts$all_node_losses) / (gl_counts$all_cat_losses / all_losses)
for (row in 1:nrow(gl_counts)) {
  if ((row %% 1000) == 0 ){
    print(row)
  }
  a <- gl_counts$gain[row]
  b <- gl_counts$non_cat_node_gains[row]
  c <- gl_counts$non_node_cat_gains[row]
  d <- gl_counts$non_cat_non_node_gains[row]
  ft <- fisher.test(matrix(c(a,b,c,d), nrow = 2, byrow = TRUE), alternative = "greater")
  gl_counts$pval_gain[row] <- ft$p.value
  gl_counts$or_gain[row]   <- ft$estimate 
  
  a <- gl_counts$loss[row]
  b <- gl_counts$non_cat_node_losses[row]
  c <- gl_counts$non_node_cat_losses[row]
  d <- gl_counts$non_cat_non_node_losses[row]
  ft <- fisher.test(matrix(c(a,b,c,d), nrow = 2, byrow = TRUE), alternative = "greater")
  gl_counts$pval_loss[row] <- ft$p.value
  gl_counts$or_loss[row]   <- ft$estimate 
}
gl_counts_fisher <- gl_counts

gl_counts <- gl_counts %>% filter(node %in% focal_nodes[1:16,]$node) # filter out non focal nodes because we are not using those tests 
gl_counts <- gl_counts %>% filter(gain > 0 | loss > 0) # remove these before we correct p values to not throw the testing correction off 

cluster_categories <- read.table("/Users/oliviatatro/Downloads/surf/GO_classifications/categories.tsv", sep = "\t", header = TRUE)

gl_counts <- rename(gl_counts, cluster = category)
gl_counts <- merge(gl_counts, cluster_categories, by.x = "cluster", by.y = "description")

gl_counts <- gl_counts %>% group_by(node, category) %>% 
  mutate(padj_gain = p.adjust(pval_gain, method = "BH"),
         padj_loss = p.adjust(pval_loss, method = "BH")) %>% 
  select(cluster, category, node, gain, loss, pval_gain, pval_loss, padj_gain, padj_loss, or_gain, or_loss, fold_gain, fold_loss)


gl_counts <- merge(gl_counts, focal_nodes, by = "node")

gl_counts <- gl_counts %>% filter(name %in% c("anth", "anth2", "endomed", "med", "endo", "myx", "hyd", "acr", "oct", "cer", "hex", "scler", "scyph", "siph", "cnid", "act"))

gl_counts$full_name <- factor(gl_counts$full_name, levels = x_axis_order)

write.table(gl_counts, file = "cluster_gl_counts.tsv", sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE)


```

```{r enrichment_plots}


# --------------------- GO categories ----------------------------

df <- read.table(file = "gl_counts.tsv", sep = "\t", header = TRUE)
summary <- read.table(file = "go_category_summary.tsv", sep = "\t", header = TRUE)
summary <- summary %>% arrange(sum_gain + sum_loss)

y_axis_order <- summary$category

df$category <- factor(df$category, levels = y_axis_order)

library(ggplot2)
library(ggbreak)
library(scales)

df$gain_color <- ifelse(df$padj_gain < 0.05, "Gain (padj < 0.05)", "Gain (n.s.)")
df$loss_color <- ifelse(df$padj_loss < 0.05, "Loss (padj < 0.05)", "Loss (n.s.)")


break_values = list("Cnidaria" = c(100, 1500, 5000), "Medusozoa" = c(10, 150, 500), "Endocnidozoa" = c(100, 2500, 10000), "Anthozoa" = c(100, 750, 2000))


colors_alpha <- c("Gain (padj < 0.05)" = "#2CA02C", 
                  "Gain (n.s.)" = adjustcolor("#2CA02C", alpha.f = 0.4), 
                  "Loss (padj < 0.05)" = "#218bc4", 
                  "Loss (n.s.)" = adjustcolor("#218bc4", alpha.f = 0.4))

plots <- list()
#focal_node <- "Anthozoa"
for (focal_node in focal_nodes$full_name[1:16]) {
  plot <- 
  ggplot(filter(df, full_name == focal_node), aes(y = category)) +
    # add 2 points per category per node: gain and loss
    geom_point(aes(x = fold_gain, size = gain, color = gain_color))+
    geom_point(aes(x = fold_loss, size = loss, color = loss_color))+
    # add verticle line for fold enrichment = 1
    geom_vline(xintercept = 1, linetype = "dashed")+
    # use the alphas vector to lighten insignificant dots
    scale_color_manual(values = colors_alpha, name = NULL) +
    theme_bw() +
    # label axes, legend, and title
    ylab(NULL)+
    xlab("Fold Enrichment") +
    labs(size = "Number of OGs") +
    ggtitle(focal_node) +
    # adjust size legend
    scale_size(range = c(1, 6), breaks = break_values[[focal_node]]) + 
    #scale_size(range = c(1, 6)) +
    # remove color legend 
    guides(size = guide_legend(override.aes = list(color = "black")),
           color = guide_legend(override.aes = list(size = 3)))+
    theme(axis.text.y = element_text(size = 12),
          axis.text.x = element_text(size = 8),
          plot.title = element_text(color = node_cols_full[focal_node], size = 16, face = "bold", margin = margin(b = -2)),
          legend.title = element_text(size = 14),
          legend.text  = element_text(size = 12, margin = margin(l = 1, unit = "pt")),
          legend.margin = margin(1, 1, 1, 1),
          legend.key.size = unit(0.3, "cm"),
          panel.border = element_rect(color = node_cols_full[focal_node], fill = NA, size = 3),
          plot.background = element_rect(fill = "white", color = NA), 
          plot.margin = margin(b = "2"))
  
  if (!focal_node %in% c("Cnidaria", "Medusozoa")) { # c("Anthozoa", "Endocnidozoa", "Octocorallia", "Scyphozoa") for 16 panel figure
    plot <- plot + theme(axis.text.y = element_blank())
  }
  if (focal_node == "Cnidaria") {
    plot <- plot + theme(legend.position = c(0.73, 0.77))
  }else {
    plot <- plot + theme(legend.position = c(0.75, 0.87)) +
      guides(color = "none")
  }
  
  print(plot)
  
  plots[[focal_node]] <- plot
}

#cowplot::plot_grid(plotlist = plots, nrow = 4, ncol = 4, rel_widths = c(2.2,1,1,1))
#ggsave(file = "../manuscript/figures/category_dotplots.png", width = 16, height = 20)


#focal_dotplots <- cowplot::plot_grid(plotlist = c(plots$Cnidaria, plots$Anthozoa, plots$Medusozoa, plots$Endocnidozoa), nrow = 2, ncol = 2, rel_widths = c(2.1,1))
#focal_dotplots
#ggsave(file = "../manuscript/figures/making_GO_figure/dotplots.png", width = 10, height = 9)

# combined dot plots
gain <- ggplot(df, aes(y = category)) +
    # add 2 points per category per node: gain and loss
    geom_jitter(aes(x = fold_gain, size = gain, color = full_name, alpha = gain_color), width = 0, height = 0.1)+
    # add verticle line for fold enrichment = 1
    geom_vline(xintercept = 1, linetype = "dashed")+
    # use the alphas vector to lighten insignificant dots
    scale_color_manual(name = "Focal node", values = node_cols_full) +
    scale_alpha_manual(values = alphas) +
    scale_x_continuous(trans = "log10") +
    scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(100, 2000, 5000)) +
    theme_bw() +
    # label axes, legend, and title
    ylab(NULL)+
    xlab("Fold Enrichment") +
    labs(size = "Number of OGs") +
    guides(alpha = "none",
           size = guide_legend(override.aes = list(color = "black")),
           color = guide_legend(override.aes = list(size = 4))) +
    theme(axis.text = element_text(size = 14),
          axis.title = element_text(size = 16),
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 14),
          legend.key.size = unit(0.6, "lines"),
          legend.key.spacing.y = unit(0, "pt"))
  
ggsave(file = "../manuscript/figures/category_gain_dotplot.png", width = 16, height = 8)

loss <- ggplot(df, aes(y = category)) +
    # add 2 points per category per node: gain and loss
    geom_jitter(aes(x = fold_loss, size = loss, color = full_name, alpha = loss_color), width = 0.0, height = 0.1)+
    # add verticle line for fold enrichment = 1
    geom_vline(xintercept = 1, linetype = "dashed")+
    # use the alphas vector to lighten insignificant dots
    scale_color_manual(name = "Focal node", values = node_cols_full) +
    scale_alpha_manual(values = alphas) +
    scale_x_continuous(trans = "log10") +
    scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(100, 4000, 10000)) +
    theme_bw() +
    # label axes, legend, and title
    ylab(NULL)+
    xlab("Fold Enrichment") +
    labs(size = "Number of OGs") +
    guides(alpha = "none",
           size = guide_legend(override.aes = list(color = "black")),
           color = guide_legend(override.aes = list(size = 4))) +
    theme(axis.text = element_text(size = 14),
          axis.title = element_text(size = 16),
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 14),
          legend.key.size = unit(0.6, "lines"),
          legend.key.spacing.y = unit(0, "pt"))
  
ggsave(file = "../manuscript/figures/category_loss_dotplot.png", width = 16, height = 8)


summary <- read.table("go_category_summary.tsv", sep = "\t", header = TRUE)
summary$category <- factor(summary$category, levels = y_axis_order)

summary <- summary %>% mutate(gain_thousands = sum_gain / 1000,
                              loss_thousands = sum_loss / 1000)

gain_summary <- ggplot(summary, aes(x = gain_thousands, y = category)) +
  geom_bar(stat = "identity", fill = "grey40", col = "black", linewidth = 0.3) +
  xlab("Number of OGs (thousands)")+
  ylab(NULL)+
  ggtitle("Gain") +
  theme_bw()+
  theme(axis.text.x = element_text(size = 8),
        axis.text.y = element_blank(),
        plot.margin = margin(t = 2, r = 7, b = 5, l = 5), 
        plot.title = element_text(size = 16, margin = margin(b = -2)))

loss_summary <- ggplot(summary, aes(x = loss_thousands, y = category)) +
  geom_bar(stat = "identity", fill = "grey80", col = "black", linewidth = 0.3) +
  xlab("Number of OGs (thousands)")+
  ylab(NULL)+
  ggtitle("Loss")+
  theme_bw()+
  theme(axis.text.x = element_text(size = 8),
        axis.text.y = element_blank(),
        plot.margin = margin(t = 2, r = 7, b = 5, l = 5),
        plot.title = element_text(size = 16, margin = margin(b = -2))) 

gain_summary
loss_summary

#left = cowplot::plot_grid(gain, loss, ncol = 1, nrow = 2, labels = c("A", "C"), label_size = 24)
#right = cowplot::plot_grid(gain_summary, loss_summary, ncol = 1, nrow = 2, labels = c("B", "D"), label_x = -0.03, label_size = 24)

#plot <- cowplot::plot_grid(left, right, ncol = 2, rel_widths = c(4,1))
#ggsave(file = "../manuscript/figures/GO_category_dotplots.png", width = 22, height = 14)


focal_dotplots <- cowplot::plot_grid(plotlist = c(plots$Cnidaria, plots$Anthozoa, gain_summary, plots$Medusozoa, plots$Endocnidozoa, loss_summary), nrow = 2, ncol = 3, rel_widths = c(2.1,1,1))
focal_dotplots
ggsave(file = "../manuscript/figures/GO_dotplots_4_nodes.png", width = 14, height = 9)

# ------------------- COGs --------------------------


df <- read.table(file = "cog_enrichment.tsv", sep = "\t", header = TRUE)
summary <- read.table(file = "cog_gain_loss_summary.tsv", sep = "\t", header = TRUE)
summary <- summary %>% arrange(gain + loss)

y_axis_order <- summary$definition

df$definition <- factor(df$definition, levels = y_axis_order)

library(ggplot2)
library(ggbreak)
library(scales)
df$gain_color <- ifelse(df$padj_gain < 0.05, "Gain (padj < 0.05)", "Gain (n.s.)")
df$loss_color <- ifelse(df$padj_loss < 0.05, "Loss (padj < 0.05)", "Loss (n.s.)")


break_values = list("Cnidaria" = c(100, 1500, 5000), "Medusozoa" = c(10, 150, 500), "Endocnidozoa" = c(100, 2500, 10000), "Anthozoa" = c(100, 750, 2000))


colors_alpha <- c("Gain (padj < 0.05)" = "#2CA02C", 
                  "Gain (n.s.)" = adjustcolor("#2CA02C", alpha.f = 0.4), 
                  "Loss (padj < 0.05)" = "#218bc4", 
                  "Loss (n.s.)" = adjustcolor("#218bc4", alpha.f = 0.4))

plots <- list()

for (focal_node in focal_nodes$full_name[1:16]) {
  plot <- 
  ggplot(filter(df, node_name == focal_node), aes(y = definition)) +
    # add 2 points per category per node: gain and loss
    geom_point(aes(x = fold_gain, size = gain, color = gain_color))+
    geom_point(aes(x = fold_loss, size = loss, color = loss_color))+
    # add verticle line for fold enrichment = 1
    geom_vline(xintercept = 1, linetype = "dashed")+
    # use the alphas vector to lighten insignificant dots
    scale_color_manual(values = colors_alpha, name = NULL) +
    theme_bw() +
    # label axes, legend, and title
    ylab(NULL)+
    xlab("Fold Enrichment") +
    labs(size = "Number of OGs") +
    ggtitle(focal_node) +
    # adjust size legend
    scale_size(range = c(1, 6), breaks = break_values[[focal_node]]) + 
    #scale_size(range = c(1, 6)) +
    # remove color legend 
    guides(size = guide_legend(override.aes = list(color = "black")),
           color = guide_legend(override.aes = list(size = 3)))+
    theme(axis.text.y = element_text(size = 12),
          axis.text.x = element_text(size = 8),
          plot.title = element_text(color = node_cols_full[focal_node], size = 16, face = "bold", margin = margin(b = -2)),
          legend.title = element_text(size = 14),
          legend.text  = element_text(size = 12, margin = margin(l = 1, unit = "pt")),
          legend.margin = margin(1, 1, 1, 1),
          legend.key.size = unit(0.3, "cm"),
          panel.border = element_rect(color = node_cols_full[focal_node], fill = NA, size = 3),
          plot.background = element_rect(fill = "white", color = NA),
          plot.margin = margin(b = 2))
  
  if (!focal_node %in% c("Cnidaria", "Medusozoa")) { # c("Anthozoa", "Endocnidozoa", "Octocorallia", "Scyphozoa") for 16 panel figure
    plot <- plot + theme(axis.text.y = element_blank())
  }
  if (focal_node == "Cnidaria") {
    plot <- plot + theme(legend.position = c(0.75, 0.795))
  }else {
    plot <- plot + theme(legend.position = c(0.77, 0.9)) +
      guides(color = "none")
  }
  
  print(plot)
  
  plots[[focal_node]] <- plot
}

#cowplot::plot_grid(plotlist = plots, nrow = 4, ncol = 4, rel_widths = c(2.2,1,1,1))
#ggsave(file = "../manuscript/figures/cog_dotplots.png", width = 16, height = 20)

gain <- ggplot(df, aes(y = definition)) +
    # add 2 points per category per node: gain and loss
    geom_jitter(aes(x = fold_gain, size = gain, color = node_name, alpha = gain_color), width = 0, height = 0.1)+
    # add verticle line for fold enrichment = 1
    geom_vline(xintercept = 1, linetype = "dashed")+
    # use the alphas vector to lighten insignificant dots
    scale_color_manual(name = "Focal node", values = node_cols_full) +
    scale_alpha_manual(values = alphas) +
    scale_x_continuous(trans = "log10") +
    scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(10, 600, 1800)) +
    theme_bw() +
    # label axes, legend, and title
    ylab(NULL)+
    xlab("Fold Enrichment") +
    labs(size = "Number of OGs") +
    guides(alpha = "none",
           size = guide_legend(override.aes = list(color = "black")),
           color = guide_legend(override.aes = list(size = 4))) +
    theme(axis.text = element_text(size = 14),
          axis.title = element_text(size = 16),
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 14),
          legend.key.size = unit(0.6, "lines"),
          legend.key.spacing.y = unit(0, "pt"))
  
loss <- ggplot(df, aes(y = definition)) +
    # add 2 points per category per node: gain and loss
    geom_jitter(aes(x = fold_loss, size = loss, color = node_name, alpha = loss_color), width = 0.0, height = 0.1)+
    # add verticle line for fold enrichment = 1
    geom_vline(xintercept = 1, linetype = "dashed")+
    # use the alphas vector to lighten insignificant dots
    scale_color_manual(name = "Focal node", values = node_cols_full) +
    scale_alpha_manual(values = alphas) +
    scale_x_continuous(trans = "log10") +
    scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(100, 2000, 5000)) +
    theme_bw() +
    # label axes, legend, and title
    ylab(NULL)+
    xlab("Fold Enrichment") +
    labs(size = "Number of OGs") +
    guides(alpha = "none",
           size = guide_legend(override.aes = list(color = "black")),
           color = guide_legend(override.aes = list(size = 4))) +
    theme(axis.text = element_text(size = 14),
          axis.title = element_text(size = 16),
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 14),
          legend.key.size = unit(0.6, "lines"),
          legend.key.spacing.y = unit(0, "pt"))


summary$definition <- factor(summary$definition, levels = y_axis_order)

summary <- summary %>% mutate(gain_thousands = gain / 1000,
                              loss_thousands = loss / 1000)

gain_summary <- ggplot(summary, aes(x = gain_thousands, y = definition)) +
  geom_bar(stat = "identity", fill = "grey40", col = "black", linewidth = 0.3) +
  xlab("Number of OGs (thousands)")+
  ylab(NULL)+
  ggtitle("Gain") +
  theme_bw()+
  theme(axis.text.x = element_text(size = 8),
        axis.text.y = element_blank(),
        plot.margin = margin(t = 2, r = 7, b = 5, l = 5), 
        plot.title = element_text(size = 16, margin = margin(b = -2)))

loss_summary <- ggplot(summary, aes(x = loss_thousands, y = definition)) +
  geom_bar(stat = "identity", fill = "grey80", col = "black", linewidth = 0.3) +
  xlab("Number of OGs (thousands)")+
  ylab(NULL)+
  ggtitle("Loss")+
  theme_bw()+
  theme(axis.text.x = element_text(size = 8),
        axis.text.y = element_blank(),
        plot.margin = margin(t = 2, r = 7, b = 5, l = 5),
        plot.title = element_text(size = 16, margin = margin(b = -2))) 

focal_dotplots <- cowplot::plot_grid(plotlist = c(plots$Cnidaria, plots$Anthozoa, gain_summary, plots$Medusozoa, plots$Endocnidozoa, loss_summary), nrow = 2, ncol = 3, rel_widths = c(2.375,1,1))
focal_dotplots
ggsave(file = "../manuscript/figures/COG_dotplots_4_nodes.png", width = 15, height = 9)

```



```{r additional_DeepFRI_plots}

df <- read.table("cluster_gl_counts.tsv", sep = "\t", header = TRUE)


library(ggplot2)
library(stringr)
library(tidytext)


# ------------------- gains at the crown cnidarian -----------------------

# these are the most notable gains at Cnidaria
cnid_clusters = data.frame(
  cluster = c("transcription regulator activity", "sequence-specific DNA binding", "RNA polymerase II transcription regulatory region sequence-specific DNA binding", 
              "transcription cis-regulatory region binding", "extracellular region", "G protein-coupled receptor signaling pathway", 
              "cell surface receptor signaling pathway", "regulation of cell communication", "intracellular signal transduction", 
              "defense response to other organism", "regulation of immune system process", "adaptive immune response", 
              "regulation of anatomical structure morphogenesis", "regulation of cell morphogenesis", "nervous system development", 
              "nervous system process", "microtubule cytoskeleton", "cytoskeleton", 
              "regulation of translation", "regulation of cell communication", "regulation of transcription by RNA polymerase II", 
              "cell differentiation", "multicellular organism development", "system development"),
                  cnid_function = c("Regulatory", "Regulatory", "Regulatory",
                                    "Regulatory", "Signaling", "Signaling",
                                    "Signaling", "Signaling", "Signaling",
                                    "Immunity", "Immunity", "Immunity", 
                                    "Development", "Development", "Nervous system", 
                                    "Nervous system", "Cnidocyte discharge", "Cnidocyte discharge",
                                    "Regulatory", "Regulatory", "Regulatory",
                                    "Development", "Development", "Development"))

# options: Immunity, Nervous System, Signaling, Regulation, Development

cnidaria <- df %>% filter(full_name == "Cnidaria") 
cnidaria <- merge(cnidaria, cnid_clusters, by = "cluster") %>% 
  mutate(cluster = str_to_sentence(cluster))


function_colors <- c("Development"              = "#C33F45",
                     "Signaling"                   = "#A3D9D9",
                     "Nervous system"                  = "#D89F58",
                     "Cnidocyte discharge"                 = "#6D3871",
                     "Regulatory"               = "#1A3567",
                     "Immunity"               = "#1c8074")

library(ggplot2)
library(stringr)
library(tidytext)
# --- Plot ---
cnid_plot <- ggplot(cnidaria, aes(x = fold_gain, y = reorder_within(cluster, fold_gain, node))) +
  geom_point(aes(size = gain, color = cnid_function)) +
  scale_color_manual(name = "Function", values = function_colors) +
  scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(50, 1000, 5000)) +
  scale_y_reordered(labels = function(x) str_wrap(gsub("___.*$", "", x), width = 50)) +
  #scale_x_continuous(limits = c(0, max(cnidaria$fold_gain))) +
  labs(x = "Fold enrichment", y = NULL) +
  theme_bw() +
  theme(
    axis.title.x = element_text(size = 12),
    axis.text.y = element_text(size = 14, lineheight = 0.7),
    strip.text.y = element_text(angle = 0, face = "bold"),
    panel.grid.minor = element_blank(),
    legend.position = "right") +
  theme(
    legend.title = element_text(size = 14),
    legend.text  = element_text(size = 12, margin = margin(l = 1, unit = "pt")),
    legend.margin = margin(1, 1, 1, 1),
    legend.key.size = unit(0.3, "cm"),
  )+
  guides(color = guide_legend(override.aes = list(size = 5)))

cnid_plot
ggsave("../manuscript/figures/crown_cnid_gains.png", width = 10, height = 8)





# ---------------------- gains in anthozoan symbiosis --------------------------
symbiosis_clusters <- data.frame(
  cluster = c("cell-cell adhesion via plasma-membrane adhesion molecules", "phagocytosis, engulfment", "phagocytosis, recognition", 
              "cell recognition", "complement activation", "ATPase-coupled ion transmembrane transporter activity", 
              "protein transmembrane transport", "metal ion transport", "phosphorelay sensor kinase activity", 
              "carbohydrate derivative binding", "vitamin binding", "endocytosis involved in viral entry into host cell", 
              "membrane fusion involved in viral entry into host cell", "activation of immune response", "adhesion of symbiont to host cell", 
              "regulation of immune system process", "defense response to other organism", "lipid transport", 
              "plasma membrane", "cell periphery", "vitamin binding", 
              "valine metabolic process", "aspartate family amino acid biosynthetic process", "lysine biosynthetic process via diaminopimelate",
              "glutamine family amino acid metabolic process", "ATPase-coupled ion transmembrane transporter activity", "protein folding", 
              "protein refolding", "immune system process", "cell periphery"), 
  node = c("Anthozoa", "Anthozoa", "Anthozoa", 
           "Anthozoa", "Anthozoa", "Anthozoa", 
           "Anthozoa", "Anthozoa", "Anthozoa", 
           "Anthozoa", "Anthozoa", "Anthozoa", 
           "Anthozoa", "Anthozoa", "Cnidaria", 
           "Cnidaria", "Cnidaria", "Ceriantheria + Hexacorallia", 
           "Ceriantheria + Hexacorallia", "Ceriantheria + Hexacorallia", "Hexacorallia", 
           "Hexacorallia", "Hexacorallia", "Hexacorallia", 
           "Hexacorallia", "Hexacorallia", "Scleractinia",
           "Scleractinia", "Ceriantheria + Hexacorallia", "Ceriantheria + Hexacorallia"), 
  symbiotic_process = c("Symbiont recognition", "Symbiont uptake", "Symbiont recognition", 
                        "Symbiont recognition", "Immune tolerance", "Nutrient exchange", 
                        "Nutrient exchange", "Nutrient exchange", "Symbiosome maintenance", 
                        "Nutrient exchange", "Nutrient exchange", "Symbiont uptake", 
                        "Symbiont uptake", "Immune tolerance", "Symbiont recognition", 
                        "Immune tolerance", "Immune tolerance", "Nutrient exchange", 
                        "Membrane remodeling", "Membrane remodeling", "Nutrient exchange",
                        "Nutrient exchange", "Nutrient exchange", "Nutrient exchange", 
                        "Nutrient exchange", "Symbiosome maintenance", "Symbiosome maintenance",
                        "Symbiosome maintenance", "Immune tolerance", "Symbiont uptake"))

# add to results that the viral genes could have been coopted 
# remove scleractinia from the results
  # frame it as there were likely smaller changes and innovations that helped refine symbiosis but the main source of innovation was calicoblasts and skeleton building.

symbiosis <- merge(df, symbiosis_clusters, by.x = c("cluster", "full_name"), by.y = c("cluster", "node"))

node_levels <- c("Cnidaria", "Anthozoa", "Ceriantheria + Hexacorallia", "Hexacorallia", "Scleractinia")

symbiosis <- symbiosis %>%
  mutate(full_name = factor(full_name, levels = node_levels)) %>%
  arrange(node, fold_gain) %>% 
  mutate(cluster = str_to_sentence(cluster))

symbiosis_colors <- c(
  "Symbiont recognition"              = "#C33F45",
  "Symbiont uptake"                   = "#A3D9D9",
  "Immune tolerance"                  = "#D89F58",
  "Nutrient exchange"                 = "#6D3871",
  "Symbiosome maintenance" = "#1A3567",
  "Membrane remodeling"               = "#1c8074"
)

symbiosis_plot <- ggplot(symbiosis, aes(x = fold_gain, y = reorder_within(cluster, fold_gain, node))) +
  geom_point(aes(size = gain, color = symbiotic_process)) +
  scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(10, 150, 500)) +
  scale_y_reordered(labels = function(x) str_wrap(gsub("___.*$", "", x), width = 50)) +
  scale_color_manual(name = "Function", values = symbiosis_colors) +
  labs(x = "Fold enrichment", y = NULL) +
  theme_bw() +
  facet_grid(full_name ~ ., scales = "free_y", space = "free_y") +
  theme(
    axis.title.x = element_text(size = 12),
    axis.text.y = element_text(size = 14, lineheight = 0.7),
    strip.text.y = element_text(angle = 0, face = "bold"),
    panel.grid.minor = element_blank(),
    legend.position = "right") +
  theme(
    legend.title = element_text(size = 14),
    legend.text  = element_text(size = 12, margin = margin(l = 1, unit = "pt")),
    legend.margin = margin(1, 1, 1, 1),
    legend.key.size = unit(0.5, "cm")
  ) +
  # hide the facets text and boxes
  theme(strip.text.y = element_blank(), strip.background = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 5)))

symbiosis_plot

ggsave("../manuscript/figures/symbiosis_gains.png", width = 10, height = 9.5)



symbiosis_colors <- c(
  "Symbiont recognition"              = "#ff598f",
  "Symbiont uptake"                   = "#ff893b",
  "Immune tolerance"                  = "#e0e300",
  "Nutrient exchange"                 = "#01dd52",
  "Symbiosome maintenance"            = "#01dddd",
  "Membrane remodeling"               = "#8a75eb"
)

# symbiosis plot for cnidofest talk
ggplot(symbiosis, aes(x = fold_gain, y = reorder_within(cluster, fold_gain, node))) +
  geom_point(aes(size = gain, color = symbiotic_process)) +
  scale_size_continuous(name = "Number of OGs", range = c(2, 10), breaks = c(10, 150, 500)) +
  scale_y_reordered(labels = function(x) str_wrap(gsub("___.*$", "", x), width = 100)) +
  scale_color_manual(name = "Function", values = symbiosis_colors) +
  labs(x = "Fold enrichment", y = NULL) +
  ggtitle("GO cluster gains support the evolution of symbiosis") +
  theme_bw() +
  facet_grid(full_name ~ ., scales = "free_y", space = "free_y") +
  theme(
    plot.title = element_text(color = "grey90", size = 24),
    axis.title.x = element_text(size = 18, color = "grey90"),
    axis.text = element_text(size = 18, lineheight = 0.7, color = "grey90"),
    strip.text.y = element_text(angle = 0, face = "bold"),
    legend.position = "right",
    legend.title = element_text(size = 24, color = "grey85"),
    legend.text  = element_text(size = 20, color = "grey85", margin = margin(l = 1, unit = "pt")),
    legend.margin = margin(1, 1, 1, 1),
    legend.key.size = unit(0.5, "cm"),
    legend.background = element_rect(fill = "black", color = NA),
    legend.key = element_rect(fill = "black", color = NA),
    panel.background = element_rect(fill = "black"),
    panel.border = element_rect(color = "white", fill = NA, linewidth = 2),
    plot.background  = element_rect(fill = "black"),
    panel.grid.major = element_line(color = "grey50"),
    panel.grid.minor = element_line(color = "grey40")
  ) +
  # hide the facets text and boxes
  theme(strip.text.y = element_blank(), strip.background = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 10)),
         size = guide_legend(override.aes = list(color = "grey85"))) 

ggsave("figures/cnidofest_cluster_symbiosis.png", width = 18, height = 11)







# ------------------ gains in Medusae evolution -------------------------------
med <- df %>% filter(full_name == "Medusozoa")

med_clusters <- data.frame(
  cluster = c("macromolecule localization", "establishment of protein localization", "signaling", 
              "nuclear division", "vesicle-mediated transport", "inorganic ion transmembrane transport",
              "secretion", "protein transport", "membrane fusion", 
              "mitochondrial electron transport", "ubiquinol to cytochrome c", "lipid biosynthetic process",
              "nervous system development", "nervous system process", "G protein-coupled receptor signaling pathway",
              "cell surface receptor signaling pathway", "intracellular signal transduction", "regulation of cell communication",
              "anatomical structure development", "regulation of developmental process", "anatomical structure development", 
              "nervous system development", "inorganic cation transmembrane transport", "establishment of localization in cell", 
              "monoatomic anion transmembrane transport", "protein transmembrane transport", "establishment of protein localization", 
              "macromolecule localization", "vesicle-mediated transport", "membrane fusion",
              "mitochondrial inner membrane", "signaling", "cell surface receptor signaling pathway", 
              "nervous system process", "anatomical structure morphogenesis", "animal organ development", 
              "proton motive force-driven plasma membrane ATP synthesis", "energy coupled proton transport down electrochemical gradient", "respiratory chain complex III", 
              "endopeptidase complex", "proteasome complex"),
  node = c("Medusozoa", "Medusozoa", "Medusozoa", 
           "Medusozoa", "Medusozoa", "Medusozoa",
           "Medusozoa", "Medusozoa", "Medusozoa", 
           "Medusozoa", "Medusozoa", "Medusozoa", 
           "Cnidaria", "Cnidaria", "Cnidaria",
           "Cnidaria", "Cnidaria", "Cnidaria",
           "Cnidaria", "Cnidaria", "Endocnidozoa + Medusozoa",
           "Endocnidozoa + Medusozoa", "Hydrozoa", "Hydrozoa",
           "Hydrozoa", "Hydrozoa", "Hydrozoa",
           "Hydrozoa", "Hydrozoa", "Hydrozoa",
           "Hydrozoa", "Acraspeda", "Acraspeda",
           "Acraspeda", "Acraspeda", "Acraspeda",
           "Scyphozoa", "Scyphozoa", "Scyphozoa",
           "Scyphozoa", "Scyphozoa"), 
  medusae_function = c("Localization", "Localization", "Signaling", 
                       "Cell proliferation", "Vesicle trafficking and secretion", "Ion transport",
                       "Vesicle trafficking and secretion", "Localization", "Vesicle trafficking and secretion",
                       "Energetics", "Energetics", "Vesicle trafficking and secretion",
                       "Nervous system development", "Nervous system development", "Signaling", 
                       "Signaling", "Signaling", "Signaling", 
                       "Development", "Development", "Development", 
                       "Nervous system development", "Ion transport", "Localization", 
                       "Ion transport", "Localization", "Localization",
                       "Localization", "Vesicle trafficking and secretion", "Vesicle trafficking and secretion", 
                       "Energetics", "Signaling", "Signaling", 
                       "Nervous system development", "Development", "Development",
                       "Energetics", "Energetics", "Energetics",
                       "Strobilation", "Strobilation"))


medusae <- merge(df, med_clusters, by.x = c("cluster", "full_name"), by.y = c("cluster", "node"))

node_levels <- c("Cnidaria", "Endocnidozoa + Medusozoa", "Medusozoa", "Hydrozoa", "Acraspeda", "Scyphozoa")

medusae <- medusae %>%
  mutate(full_name = factor(full_name, levels = node_levels)) %>%
  arrange(node, or_gain) %>% 
  mutate(cluster = str_to_sentence(cluster))

library(tidytext)

medusae_colors <- c(
  "Nervous system development"              = "#C33F45",
  "Signaling"                   = "#A3D9D9",
  "Development"                  = "#D89F58",
  "Cell proliferation"                 = "#6D3871",
  "Vesicle trafficking and secretion" = "#1A3567",
  "Ion transport"               = "#1c8074",
  "Localization"  = "#B0D19A",
  "Energetics"  = "#E2B0A5")

library(ggbreak)
medusae_plot <- ggplot(medusae, aes(x = fold_gain, y = reorder_within(cluster, fold_gain, node))) +
  geom_point(aes(size = gain, color = medusae_function)) +
  scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(10, 250, 750)) +
  scale_y_reordered(labels = function(x) str_wrap(gsub("___.*$", "", x), width = 50)) +
  #scale_x_continuous(limits = c(0, max(medusae$fold_gain))) +
  scale_color_manual(name = "Function", values = medusae_colors) +
  labs(x = "Fold enrichment", y = NULL) +
  theme_bw() +
  facet_grid(full_name ~ ., scales = "free_y", space = "free_y") +
  theme(
    axis.title.x = element_text(size = 12),
    axis.text.y = element_text(size = 14, lineheight = 0.7),
    strip.text.y = element_text(angle = 0, face = "bold"),
    panel.grid.minor = element_blank(),
    legend.position = "right") +
  theme(
    legend.title = element_text(size = 14),
    legend.text  = element_text(size = 12, margin = margin(l = 1, unit = "pt")),
    legend.margin = margin(1, 1, 1, 1),
    legend.key.size = unit(0.5, "cm")
  ) +
  # hide the facets text and boxes
  theme(strip.text.y = element_blank(), strip.background = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  scale_x_break(c(2.75, 15), scales = 0.2) +
  theme(axis.text.y.right = element_blank(), # the break adds extra labels for some reason. so, removing them here
        axis.ticks.y.right = element_blank())

medusae_plot

ggsave("../manuscript/figures/medusae_gains.png", width = 10.5, height = 11.5)





# ------------------ evolution of parasitism -------------------------------
endo <- df %>% filter(full_name == "Myxozoa") %>%  filter(padj_gain < 0.05)

parasite_clusters <- data.frame(
  cluster = c("regulation of cell morphogenesis", "ribonucleoprotein complex biogenesis", "regulation of translation", 
              "multicellular organismal process", "cellular component organization", "G protein-coupled receptor signaling pathway",
              "intracellular signal transduction", "cell differentiation", "cellular response to chemical stimulus", 
              "potassium ion transmembrane transport", "cell surface receptor signaling pathway", "regulation of transcription by RNA polymerase II",
              "immune response-regulating cell surface receptor signaling pathway", "developmental process", "positive regulation of multicellular organismal process", 
              "nervous system development", "nervous system process", "regulation of immune response", 
              "primary active transmembrane transporter activity", "proton-transporting ATP synthase activity, rotational mechanism", "active transmembrane transporter activity", 
              "microtubule cytoskeleton organization", "cellular component organization", "protein-RNA complex assembly", 
              "multicellular organism development", "nervous system process", "anatomical structure development", 
              "cell differentiation", "adaptive immune response", "nervous system development", 
              "multicellular organismal process", "transmembrane transporter activity", "primary active transmembrane transporter activity",
              "ATPase-coupled transmembrane transporter activity"),
  parasitism_function = c("Development", "Translation", "Regulation",
                       "Organization", "Organization", "Nervous system", 
                       "Signaling", "Development", "Response", 
                       "Nervous system", "Signaling", "Regulation", 
                       "Immune system", "Development", "Regulation",
                       "Nervous system", "Nervous system", "Immune system",
                       "Transporters", "Energy production", "Transporters", 
                       "Organization", "Organization", "Translation",
                       "Organization", "Nervous system", "Development",
                       "Development", "Immune system", "Nervous system",
                       "Organization", "Transporters", "Transporters", 
                       "Transporters"), 
  node = c("Endocnidozoa", "Endocnidozoa", "Endocnidozoa",
                 "Endocnidozoa", "Endocnidozoa", "Endocnidozoa",
                 "Endocnidozoa", "Endocnidozoa", "Endocnidozoa",
                 "Endocnidozoa", "Endocnidozoa", "Endocnidozoa", 
                 "Endocnidozoa", "Endocnidozoa", "Endocnidozoa",
                 "Endocnidozoa", "Endocnidozoa", "Endocnidozoa", 
                 "Endocnidozoa", "Endocnidozoa", "Endocnidozoa",
                 "Myxozoa", "Myxozoa", "Myxozoa", 
                 "Myxozoa", "Myxozoa", "Myxozoa",
                 "Myxozoa", "Myxozoa", "Myxozoa",
                 "Myxozoa", "Myxozoa", "Myxozoa",
                 "Myxozoa"),
  node_event = c("Endocnidozoa Loss", "Endocnidozoa Loss", "Endocnidozoa Loss",
                 "Endocnidozoa Loss", "Endocnidozoa Loss", "Endocnidozoa Loss",
                 "Endocnidozoa Loss", "Endocnidozoa Loss", "Endocnidozoa Loss",
                 "Endocnidozoa Loss", "Endocnidozoa Loss", "Endocnidozoa Loss", 
                 "Endocnidozoa Loss", "Endocnidozoa Loss", "Endocnidozoa Loss", 
                 "Endocnidozoa Loss", "Endocnidozoa Loss", "Endocnidozoa Loss", 
                 "Endocnidozoa Gain", "Endocnidozoa Gain", "Endocnidozoa Gain",
                 "Myxozoa Loss", "Myxozoa Loss", "Myxozoa Loss", 
                 "Myxozoa Loss", "Myxozoa Loss", "Myxozoa Loss", 
                 "Myxozoa Loss", "Myxozoa Loss", "Myxozoa Loss", 
                 "Myxozoa Loss", "Myxozoa Gain", "Myxozoa Gain",
                 "Myxozoa Gain"),
  event = c("Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Gain", "Gain", "Gain",
                 "Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Loss", "Loss", "Loss",
                 "Loss", "Gain", "Gain",
                 "Gain"))

parasitism <- merge(df, parasite_clusters, by.x = c("cluster", "full_name"), by.y = c("cluster", "node"))
parasitism$fold <- ifelse(parasitism$event == "Gain", parasitism$fold_gain, parasitism$fold_loss)

node_levels <- c("Endocnidozoa Loss", "Endocnidozoa Gain", "Myxozoa Loss", "Myxozoa Gain")

parasitism <- parasitism %>%
  mutate(full_name = factor(node_event, levels = node_levels)) %>%
  arrange(node, or_gain) %>% 
  mutate(cluster = str_to_sentence(cluster))

library(tidytext)

parasitism_colors <- c(
  "Nervous system"              = "#C33F45",
  "Signaling"                   = "#A3D9D9",
  "Development"                  = "#D89F58",
  "Immune system"                 = "#6D3871",
  "Organization" = "#1A3567",
  "Transporters"               = "#1c8074",
  "Response"  = "#B0D19A",
  "Energy production"  = "#E2B0A5")

library(ggbreak)
parasitism_plot <- ggplot(parasitism, aes(x = fold, y = reorder_within(cluster, fold, node_event))) +
  geom_point(aes(size = gain, color = parasitism_function)) +
  geom_point(aes(size = loss, color = parasitism_function)) +
  scale_size_continuous(name = "Number of OGs", range = c(2, 8), breaks = c(10, 500, 2000)) +
  scale_y_reordered(labels = function(x) str_wrap(gsub("___.*$", "", x), width = 50)) +
  #scale_x_continuous(limits = c(0, max(medusae$fold))) +
  scale_color_manual(name = "Function", values = parasitism_colors) +
  labs(x = "Fold enrichment", y = NULL) +
  theme_bw() +
  facet_grid(full_name ~ ., scales = "free_y", space = "free_y") +
  theme(
    axis.title.x = element_text(size = 12),
    axis.text.y = element_text(size = 14, lineheight = 0.7),
    strip.text.y = element_text(angle = 0, face = "bold"),
    panel.grid.minor = element_blank(),
    legend.position = "right") +
  theme(
    legend.title = element_text(size = 14),
    legend.text  = element_text(size = 12, margin = margin(l = 1, unit = "pt")),
    legend.margin = margin(1, 1, 1, 1),
    legend.key.size = unit(0.5, "cm")
  ) +
  # hide the facets text and boxes
  theme(strip.text.y = element_blank(), strip.background = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  scale_x_break(c(1.6, 7), scales = 0.2) +
  theme(axis.text.y.right = element_blank(), # the break adds extra labels for some reason. so, removing them here
        axis.ticks.y.right = element_blank())

parasitism_plot
ggsave("../manuscript/figures/parasitism_evolution.png", width = 10, height = 10.5)


# cnid_plot   symbiosis_plot
# medusae_plot   parasitism_plot

left <- cowplot::plot_grid(cnid_plot, medusae_plot, ncol = 1, rel_heights = c(nrow(cnidaria), nrow(medusae)))
right <- cowplot::plot_grid(symbiosis_plot, parasitism_plot, ncol = 1, rel_heights = c(nrow(symbiosis), nrow(parasitism)))
full <- cowplot::plot_grid(left, right, nrow = 1)
full
ggsave("../manuscript/figures/GO_clusters.png", width = 16, height = 20)
```








```{r go_cluster_enrichment, eval=FALSE}
# group and sum the go data so that each row has a node, gain/loss, category, and the total count of annotations
clusters <- gofigure_data %>% 
  group_by(node, event, category) %>% 
  summarize(sum_size = sum(size))

# fishertest: IF EACH GO CATEGORY IS GAINED/LOST MORE IN THIS NODE THAN IN OTHER NODES
    # a = number of category gains in thisnode
    # b = number of other category gained in thisnode
    # c = number of category gains in other nodes
    # d = number of other category gains in other nodes 
clusters$pval <- NA

for (i in 1:nrow(clusters)) {
  print(i)
  this_node = clusters$node[i]
  this_event = clusters$event[i]
  this_category = clusters$category[i]
  
  b_total <- sum(filter(clusters, node == this_node, event == this_event)$sum_size)
  d_total <- sum(filter(clusters, event == this_event)$sum_size)
  # cnid metabolic gains
  a <- filter(clusters, node == this_node, event == this_event, category == this_category)$sum_size[1]
  # cnid gains that are NOT metabolic
  b <- b_total - a
  # metabolic gains from all nodes except cnid 
  c <- sum(filter(clusters, event == this_event, category == this_category)$sum_size) - a
  # gains that are not metabolic and not in the cnid node
  d <- d_total - a - b -c
  mat <- matrix(c(a,b,c,d),nrow = 2, byrow = TRUE)
  p <- fisher.test(mat, alternative = "greater")$p.value
  
  clusters$pval[i] <- p 
  
}
clusters$padj <- p.adjust(clusters$pval, method = "bonferroni")

# create a named vector of the categories and the x value I am assigning 
category_nums <- c(`Behavior and Movement` = 1, 
                  `Cell Communication and Signaling` = 2, 
                  `Cell Cycle and Division` = 3,
                  `Development` = 4,
                  `Gene Expression and Regulation` = 5,
                  `Immune Response` = 6,
                  `Metabolism` = 7,
                  `Response to Stress and Stimuli` = 8,
                  `Nutrient Uptake and Exchange` = 9,
                  `Energy Production and Conversion` = 10,
                  `Homeostasis` = 11,
                  `Structural Organization and Cytoskeleton` = 12,
                  `Reproduction` = 13, 
                  `Nervous Systen Processes` = 14, 
                  `Cellular Transport and Localization` = 15)

# assign the number value of the category to a new column in clusters df called x
clusters$x <- category_nums[clusters$category]
# create a new column that is the same as sumsize if it is significant, but otherwise it is just 0
clusters$sig_bar <- ifelse(clusters$padj < 0.01, clusters$sum_size, 0)
# invert to make the losses below x axis
clusters$sig_bar <- ifelse(clusters$event == "loss", -1 * clusters$sig_bar, clusters$sig_bar)
clusters$bar <- ifelse(clusters$event == "loss", -1 * clusters$sum_size, clusters$sum_size)
# plot the grey and then plot the color in two separate geom_bars

colnames(clusters) # "node"     "event"    "category" "sum_size" "pval"     "padj"     "x"        "sig_bar" 

pdf("../figures/GO_cluster_enrichment_by_category.pdf", width = 12, height = 8)
ggplot(data = clusters) +
  geom_bar(aes(x = node, y = bar/1000000), stat = "identity", fill = "grey70", size = 0.01, width = 0.9) +
  geom_bar(aes(x = node, y = sig_bar/1000000, fill = category), size = 0.01, stat = "identity", width = 0.9) +
  scale_fill_manual(values = named_colors) +
  ylab("Number of centroids (Millions)") +
  xlab("GO cluster category") +
  facet_wrap(~ category, scales = "free_y", ncol = 3) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 8))
dev.off()

pdf("../figures/GO_cluster_enrichment_by_node.pdf", width = 12, height = 8)
ggplot(data = clusters) +
  geom_bar(aes(x = x, y = bar/1000000), stat = "identity", fill = "grey70", size = 0.01, width = 0.9) +
  geom_bar(aes(x = x, y = sig_bar/1000000, fill = category), size = 0.01, stat = "identity", width = 0.9) +
  scale_fill_manual(values = named_colors) +
  ylab("Number of centroids (Millions)") +
  xlab("GO cluster category") +
  facet_wrap(~ node, scales = "free_y", ncol = 3) +
  theme_bw() 
dev.off()

# [1] "Behavior and Movement"                    "Cell Communication and Signaling"        
# [3] "Cell Cycle and Division"                  "Cellular Transport and Localization"     
# [5] "Development"                              "Energy Production and Conversion"        
# [7] "Gene Expression and Regulation"           "Homeostasis"                             
# [9] "Immune Response"                          "Metabolism"                              
#[11] "Nutrient Uptake and Exchange"             "Response to Stress and Stimuli"          
#[13] "Structural Organization and Cytoskeleton"
test <- filter(gofigure_data, node == "endo", category == "Structural Organization and Cytoskeleton")

```

#NOT WORKING YET
```{r go_enrichment_tree}

# GAIN ----------------------------------------------------------------------
library(tidyr)
test <- clusters %>% filter(event == "gain") %>% ungroup() %>% 
  select(node, sig_bar, category) %>% 
  pivot_wider(names_from = category, values_from = sig_bar, values_fill = 0)

COG_matrix <- COG_matrix[,order(colnames(COG_matrix))]
COG_matrix <- COG_matrix[,-c(23)] #remove X 

pie_sizes <- rowSums(COG_matrix)
pie_sizes[151] <- 0 #Setting myriazoa  to 0
pie_sizes[127] <- 0 #Setting planulazoa  to 0
pie_sizes[85] <- 0 #Setting cnidaria  to 0
pie_sizes <- pie_sizes[-(1:76)]
pie_sizes <- pie_sizes^(1/2)
pie_sizes <- pie_sizes / max(pie_sizes) *2.5

for (i in 77:151) {
  print(i)
  df <- COG_setup(i) %>% 
    filter(padj_gain < 0.01)
  for (cog in colnames(COG_matrix)) {
    if (!(cog %in% df$COG_term)) {
      COG_matrix[i, cog] <- 0
    }
  }
}

COG_matrix <- COG_matrix / rowSums(COG_matrix)
COG_matrix <- as.matrix(COG_matrix)

# the original cog_matrix did not work properly because a bunch of the pies were one color, but this manually matches the internal nodes to the rows in COG_matrix
internal_nodes <- as.character((Ntip(tree) + 1):(Ntip(tree) + Nnode(tree)))
COG_matrix_ordered <- COG_matrix[internal_nodes, ]

pdf("../figures/COGs/g_COG_tree_piesizes.pdf", width = 8, height = 8)
plot(tree, cex = 0.5) ; nodelabels(pie = COG_matrix_ordered,
           node = as.numeric(rownames(COG_matrix_ordered)),
           piecol = cog_colors,
           cex = pie_sizes[rownames(COG_matrix_ordered)]) ; legend(x = 1.2, y = 50, legend = cog_labels, fill = cog_colors, ncol = 1, cex = 0.6)
#plot(tree, cex = 0.5, no.margin = TRUE) ;nodelabels()
dev.off()

plot(tree, cex = 0.5)
nodelabels()

# LOSS ----------------------------------------------------------------------

for (NODE in 1:151) {
  if (is.null(COGs[[NODE,3]])){
    COGs[NODE,3] <- c("X")
  }
}

#make the COG matrix with each cog category being a column and the nodes beign the rows 
COG_matrix <- COGs %>%
  dplyr::select(-g_COGs) %>% 
  unnest(l_COGs) %>%
  group_by(node, l_COGs) %>%
  summarize(count = n(), .groups = "drop") %>% 
  pivot_wider(names_from = l_COGs, values_from = count, values_fill = 0) %>%
  column_to_rownames("node")

COG_matrix <- COG_matrix[,order(colnames(COG_matrix))]
COG_matrix <- COG_matrix[,-c(23)] #remove X 

pie_sizes <- rowSums(COG_matrix)
#pie_sizes[151] <- 0 #Setting myriazoa  to 0
#pie_sizes[127] <- 0 #Setting planulazoa  to 0
#pie_sizes[85] <- 0 #Setting cnidaria  to 0
pie_sizes <- pie_sizes[-(1:76)]
pie_sizes <- pie_sizes^(1/2)
pie_sizes <- pie_sizes / max(pie_sizes) * 2

for (i in 77:151) {
  print(i)
  df <- COG_setup(i) %>% 
    filter(padj_loss < 0.01)
  for (cog in colnames(COG_matrix)) {
    if (!(cog %in% df$COG_term)) {
      COG_matrix[i, cog] <- 0
    }
  }
}

COG_matrix <- COG_matrix / rowSums(COG_matrix)
COG_matrix <- as.matrix(COG_matrix)

# the original cog_matrix did not work properly because a bunch of the pies were one color, but this manually matches the internal nodes to the rows in COG_matrix
internal_nodes <- as.character((Ntip(tree) + 1):(Ntip(tree) + Nnode(tree)))
COG_matrix_ordered <- COG_matrix[internal_nodes, ]

pdf("../figures/COGs/l_COG_tree_piesizes.pdf", width = 8, height = 8)
plot(tree, cex = 0.5) ; nodelabels(pie = COG_matrix_ordered,
           node = as.numeric(rownames(COG_matrix_ordered)),
           piecol = cog_colors,
           cex = pie_sizes[rownames(COG_matrix_ordered)]) ; legend(x = 1.2, y = 50, legend = cog_labels, fill = cog_colors, ncol = 1, cex = 0.6)
#plot(tree, cex = 0.5, no.margin = TRUE) ;nodelabels()
dev.off()


```


```{r bubble_tree, message=FALSE, warning=FALSE}

load("../orthodollo/tree.Rds")
tree <- tr1
rm(tr1)


#load("/Users/oliviatatro/Downloads/surf/eggnog/eggnog_met.Rdata") 
setwd("/Users/oliviatatro/Downloads/surf/deepfri/go_figure_tsvs50/")

library(ggforce)

#NODE = 85
DOTS <- "/Users/oliviatatro/Downloads/surf/deepfri/go_figure_tsvs/anth/gain/biological_process_anth__gain.tsv"
#CATS <- "/Users/oliviatatro/Downloads/surf/deepfri/go_figure/BP_classified.csv" 


library(ggtree)
tree_plot <- ggtree(tree, branch.length = "none") + 
  geom_tiplab(size = 4, align = TRUE) +
  scale_y_reverse() +
  theme(plot.margin = margin(t = 5, r = 40, b = 5, l = 5)) +
  coord_cartesian(clip = "off") 

tree_data <- tree_plot$data

collapse_nodes <- data.frame(
  node = c(130, 82, 91, 117, 113, 136, 100, 104, 109, 134, 142),
  label = c("Myxozoa", " Hydrozoa", "Scleractinia", " Octocorallia", "Ceriantheria", " Scyphozoa", "Corallimorpharia", "Actinaria", "Zoantheria", "Cubozoa", "Staurozoa")
)

xright <- filter(tree_data, isTip == TRUE)$x[1]

segments <- data.frame(x = numeric(), xend = numeric(), y = numeric(), yend = numeric())

for (i in 1:nrow(collapse_nodes)) {
  node <- collapse_nodes$node[i]
  label <- collapse_nodes$label[i]
  tree_plot <- collapse(tree_plot, node = node)
  tree_data <- tree_plot$data
  xstart <- tree_data$x[tree_data$node == node] # x coord of the node
  extend <- (xright - xstart - 0.285)
  tree_plot <- tree_plot + 
    geom_cladelabel(node = node, label = label, offset = extend, barsize = 1) 
}
for (i in 1:nrow(collapse_nodes)) {
  node <- collapse_nodes$node[i]
  xstart <- tree_data$x[tree_data$node == node] # x coord of the node
  y <- tree_data$y[tree_data$node == node]
  segments <- rbind(segments, data.frame(x = xstart, xend = xright, y = y, yend = y))
}

tree_plot <- tree_plot + geom_segment(data = segments, aes(x = x, xend = xend, y = y, yend = yend))

gofigureplot <- function(NODE, EVENT) {
  dots <- gofigure_data %>% filter(node == NODE, event == EVENT) 
  plot <- ggplot() +
    geom_circle(data = filter(dots, pval >= 0.01), aes(x0 = x, y0 = y, r = log(size)/30, fill = I("grey70"), col = I("grey70")), stroke = 0.1, alpha = 0.3) +
    geom_circle(data = filter(dots, pval < 0.01), aes(x0 = x, y0 = y, r = log(size)/30, fill = category, col = category), stroke = 0.1, alpha = 0.7) +
    scale_fill_manual(values = named_colors) +
    scale_color_manual(values = named_colors) +
    scale_x_continuous(limits = c(-2,2)) +
    scale_y_continuous(limits = c(-2,2)) +
    theme_void() +
    theme(legend.position = "none", plot.margin = unit(c(0, 0, 0, 0), "cm"), 
          axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank(),
          panel.border = element_rect(size = 1, color = "black", fill = NA),
          panel.background = element_rect(fill = "white", color = NA))
  return(plot) 
}

square_size <- 0.65



gain_tree_plot <- tree_plot
for (i in 1: nrow(focal_nodes)){
  goplot <- gofigureplot(focal_nodes$node_name_full[i],"gain")
  grob_goplot <- ggplotGrob(goplot)
  print(grob_goplot)
  thisnode <-focal_nodes$node_number[i]
  x <- tree_data[tree_data$node == thisnode, ]$x
  y <- tree_data[tree_data$node == thisnode, ]$y
  gain_tree_plot <- gain_tree_plot + 
      annotation_custom(grob = grob_goplot, xmin = x - square_size, xmax = x + square_size, ymin = -y - square_size, ymax = -y + square_size) 
}

loss_tree_plot <- tree_plot
for (i in 1: nrow(focal_nodes)){
  goplot <- goplot <- gofigureplot(focal_nodes$node_name_full[i],"loss")
  grob_goplot <- ggplotGrob(goplot)
  print(grob_goplot)
  thisnode <-focal_nodes$node_number[i]
  x <- tree_data[tree_data$node == thisnode, ]$x
  y <- tree_data[tree_data$node == thisnode, ]$y
  loss_tree_plot <- loss_tree_plot + 
      annotation_custom(grob = grob_goplot, xmin = x - square_size, xmax = x + square_size, ymin = -y - square_size, ymax = -y + square_size) 
}
loss_tree_plot

grob_legend_dots <- ggplotGrob(legend_dots)
grob_legend_text <- ggplotGrob(legend_text)
loss_tree_plot <- loss_tree_plot + 
  annotation_custom(grob = grob_legend_dots, xmin = -0.5, xmax = -0.25, ymin = -16, ymax = -9.75) +
  annotation_custom(grob = grob_legend_text, xmin = -0.25, xmax = 4, ymin = -16, ymax = -9.75) 
gain_tree_plot <- gain_tree_plot + 
  annotation_custom(grob = grob_legend_dots, xmin = -0.5, xmax = -0.25, ymin = -16, ymax = -9.75) +
  annotation_custom(grob = grob_legend_text, xmin = -0.25, xmax = 4, ymin = -16, ymax = -9.75) 

# 12.5 height to 8 width

pdf("/Users/oliviatatro/Downloads/surf/figures/deepfri_GOs/bubble_trees.pdf", height = 12, width = 12)
gain_tree_plot
loss_tree_plot
dev.off()

write_csv(filter(gofigure_data, pval < 0.01), "../go_figure_data_sig.csv")
write_csv(gofigure_data, "../go_figure_data_all.csv")

```

creates a histogram of all of the scores (1 per annotation) from the deepfri data and it is colored by ontology

```{r scores}
library(ggplot2)
library(dplyr)

ontology_colors <- c("BP" = "palevioletred", "CC" = "steelblue3", "MF" = "seagreen3", "all" = "orange2")

dir = "/Users/oliviatatro/Downloads/surf/deepfri/"

bp <- read.csv(file.path(dir, "BP.head.csv"), header = FALSE)
cc <- read.csv(file.path(dir, "CC.head.csv"), header = FALSE)
mf <- read.csv(file.path(dir, "MF.head.csv"), header = FALSE)

colnames(bp) <- c("Protein", "GO", "Score", "Description")
colnames(cc) <- c("Protein", "GO", "Score", "Description")
colnames(mf) <- c("Protein", "GO", "Score", "Description")

bp$Ontology = "BP"
cc$Ontology = "CC"
mf$Ontology = "MF"

data <- rbind(bp, cc, mf)

#pdf("../figures/score_histogram.pdf", height = 5, width = 8)
ggplot(data = data, aes(x = Score, fill = Ontology)) +
  geom_histogram(bins = 30, col = "black") +
  scale_fill_manual(values = ontology_colors) +
  xlab("DeepFRI score") +
  ylab("Number of annotations") +
  theme_bw()
#dev.off()

# okay so my goal is to create a scoores df with columns filter count and ontology 
  # count is the number of annotations that are above the filter for the deepfri score 
scores <- data.frame(filter = character(), count = numeric(), ontology = character())

for (thisfilter in c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)) {
  # total of all the ontologies
  uniq_count <- data %>% filter(Score >= thisfilter) %>% distinct(Protein) %>% nrow()
  scores <- rbind(scores, data.frame(filter = thisfilter, ontology = "all", count = uniq_count))
  # biological process
  uniq_count <- bp %>% filter(Score >= thisfilter) %>% distinct(Protein) %>% nrow()
  scores <- rbind(scores, data.frame(filter = thisfilter, ontology = "BP", count = uniq_count))
  # cellular component
  uniq_count <- cc %>% filter(Score >= thisfilter) %>% distinct(Protein) %>% nrow()
  scores <- rbind(scores, data.frame(filter = thisfilter, ontology = "CC", count = uniq_count))
  # molecular function
  uniq_count <- mf %>% filter(Score >= thisfilter) %>% distinct(Protein) %>% nrow()
  scores <- rbind(scores, data.frame(filter = thisfilter, ontology = "MF", count = uniq_count))
  write.csv(scores, file="myscores.csv")
}

ggplot(data = scores, aes(x = as.character(filter), y = count, fill = ontology)) +
  geom_bar(stat = "identity", position = position_dodge(), col = "black") +
  geom_hline(yintercept = 197, linetype = "dashed") +
  scale_fill_manual(values = ontology_colors) +
  xlab("DeepFRI Score Filter") +
  ylab("Number of centroids annotated") +
  annotate("text", x = 7.5, y = 205, label = "Total number of centroids", size = 5) +
  theme_bw()


ggplot(data = scores, aes(x = as.character(filter), y = count/1000000, fill = ontology)) +
  geom_bar(stat = "identity", position = position_dodge(), col = "black") +
  geom_hline(yintercept = 2684787/1000000, linetype = "dashed") +
  scale_fill_manual(values = ontology_colors) +
  xlab("DeepFRI Score Filter") +
  ylab("Number of centroids annotated (millions)") +
  annotate("text", x = 7.5, y = 2.8, label = "Total number of centroids", size = 5) +
  theme_bw()

```






